

---


**MÁSTER UNIVERSITARIO EN DATA ANALYTICS FOR BUSINESS** | **UPF Barcelona School of Management** | **Curso 2023-2024**

**Trabajo Final de Máster**

**Título del proyecto**: Análisis exploratorio de accidentes de tráfico en Barcelona

**Script**: Limpieza de datos

**Autores**: Joel Bullich Esquerra y Pablo García Prado

**Mentora**: Alexandra Abós Ortega


---

## Importación de librerías

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
import seaborn as sns
import os
import random
from tabulate import tabulate

from google.colab import drive
drive.mount('/content/drive')

pd.set_option('display.max_columns', None)

Mounted at /content/drive

## Tratamiento de los *datasets*

### Anexionar los *datasets* del mismo tipo

La totalidad de nuestro conjunto de datos está almacenado en seis carpetas distintas de *Drive*, donde en cada una de ellas hay siete archivos .csv con información correspondiente a accidentes de tráfico. Los datos están almacenados en carpetas distintas porque en cada una se tratan variables distintas de cada accidente.

Para empezar, queremos pasar de tener 42 archivos a tener solamente 6 y así facilitar el tratamiento y limpieza. Entonces, vamos a anexar las observaciones de los que comparten exactamente las mismas variables.

In [ ]:
# Cambia al directorio que contiene las carpetas
os.chdir('/content/drive/MyDrive/TFM/raw_data')

# Lista para almacenar los DataFrames resultantes
dataframes = []

# Iterar sobre cada carpeta
for folder in os.listdir():
    if os.path.isdir(folder):
        # Crear una lista para almacenar los DataFrames de los archivos CSV de esta carpeta
        dfs = []
        # Iterar sobre los archivos CSV en la carpeta actual
        for file in os.listdir(folder):
            if file.endswith('.csv'):
                # Leer el archivo CSV y agregarlo a la lista
                df = pd.read_csv(os.path.join(folder, file))
                dfs.append(df)
        # Combinar los DataFrames en uno solo y agregarlo a la lista de DataFrames
        combined_df = pd.concat(dfs, ignore_index=True)
        dataframes.append(combined_df)

# Guardar cada DataFrame de la lista dataframes con nombres df_1, df_2, etc.
for i, df in enumerate(dataframes, start=1):
    globals()[f"df_{i}"] = df

Ahora tenemos seis *dataframes* distintos. El objetivo será juntar todos estos datasets, una vez limpios, a un único dataset.

In [ ]:
path = "/content/drive/MyDrive/TFM/raw_data/1/download.csv"
df1 = pd.read_csv(path)

path = "/content/drive/MyDrive/TFM/raw_data/1/download-2.csv"
df2 = pd.read_csv(path)

path = "/content/drive/MyDrive/TFM/raw_data/1/download-3.csv"
df3 = pd.read_csv(path)

path = "/content/drive/MyDrive/TFM/raw_data/1/download-4.csv"
df4 = pd.read_csv(path)

path = "/content/drive/MyDrive/TFM/raw_data/1/download-5.csv"
df5 = pd.read_csv(path)

path = "/content/drive/MyDrive/TFM/raw_data/1/download-6.csv"
df6 = pd.read_csv(path)

path = "/content/drive/MyDrive/TFM/raw_data/1/download-7.csv"
df7 = pd.read_csv(path)

In [ ]:
print(df1.shape)
print(df2.shape)
print(df3.shape)
print(df4.shape)
print(df5.shape)
print(df6.shape)
print(df7.shape)

(10510, 20)
(11091, 20)
(10835, 20)
(11025, 20)
(7595, 20)
(8979, 20)
(9320, 20)

In [ ]:
df_6.shape

(79647, 46)

### Análisis de los datasets para eliminar columnas repetidas

Con el objetivo de juntar los 7 datasets en un único dataset, en este apartado analizaremos cada uno de los datasets para ver si existen columnas duplicadas que podemos eliminar. Para poder ver el formato de los valores de las columnas de cada *dataframe*, hemos creado una función que muestra cinco valores aleatorios de cada una de las variables (excluyendo los valores nulos). Esta, nos va a permitir ver, más gráficamente que utilizando *.unique()*, cuáles podrían ser las columnas que contienen el mismo tipo de información (columnas duplicadas) más allá de su nombre.

In [ ]:
# Definimos la función
def mostrar_valores_unicos_aleatorios_tabla(df):
    tabla_valores_unicos = [] #creamos una lista que servirá para luego montarla en formato tabular

    for columna in df.columns: #recorremos cada columa de nuestro df
        valores_unicos = df[columna].dropna().unique()  # Para cada columna, eliminamos los NaN y obtemos los valores únicos
        if len(valores_unicos) > 5: #si tenemos, por lo menos, 5 valores únicos...
            valores_unicos_aleatorios = random.sample(list(valores_unicos.astype(str)), 5)  # Convertimos a cadena y escoger 5 valores aleatorios únicos
        else: #si hay más de cinco, lo convertimos a tipo string
            valores_unicos_aleatorios = valores_unicos.astype(str)
        # Truncamos las cadenas de caracteres a una longitud fija de 20 (max) para evitar errores en la tabulación
        valores_unicos_aleatorios = [valor[:20] for valor in valores_unicos_aleatorios]
        tabla_valores_unicos.append([columna] + valores_unicos_aleatorios) #añadimos a nuestra lista el nombre de las columnas junto a los 5 valores aleatorios

    # Imprimimos la tabla utilizando tabulate y escogemos los títulos de los encabezados
    print(tabulate(tabla_valores_unicos, headers=["Columna", "Valor 1", "Valor 2", "Valor 3", "Valor 4", "Valor 5"]))

#### *Dataframe* tipo 1

In [ ]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69355 entries, 0 to 69354
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Numero_expedient            69355 non-null  object
 1   Codi_districte              69355 non-null  int64
 2   Nom_districte               69355 non-null  object
 3   Codi_barri                  69355 non-null  int64
 4   Nom_barri                   69355 non-null  object
 5   Codi_carrer                 69355 non-null  int64
 6   Nom_carrer                  69354 non-null  object
 7   Num_postal                  69339 non-null  object
 8   Descripcio_dia_setmana      69355 non-null  object
 9   NK_Any                      69355 non-null  int64
 10  Mes_any                     69355 non-null  int64
 11  Nom_mes                     69355 non-null  object
 12  Dia_mes                     69355 non-null  int64
 13  Hora_dia                    69355 non-null  int64
 14  Descripcio_torn             69355 non-null  object
 15  Descripcio_causa_conductor  51056 non-null  object
 16  Coordenada_UTM_X_ED50       69355 non-null  float64
 17  Coordenada_UTM_Y_ED50       69355 non-null  float64
 18  Longitud                    69325 non-null  float64
 19  Latitud                     69325 non-null  float64
 20  Descripcio_causa_mediata    18299 non-null  object
dtypes: float64(4), int64(7), object(10)
memory usage: 11.1+ MB

In [ ]:
mostrar_valores_unicos_aleatorios_tabla(df_1)

Columna                     Valor 1               Valor 2               Valor 3               Valor 4               Valor 5
--------------------------  --------------------  --------------------  --------------------  --------------------  --------------------
Numero_expedient            2019S009387           2020S005140           2022S003736           2019S007153           2022S005029
Codi_districte              5                     3                     8                     4                     1
Nom_districte               Les Corts             Sant Martí            Desconegut            Sants-Montjuïc        Sant Andreu
Codi_barri                  53                    61                    14                    9                     10
Nom_barri                   la Marina de Port     la Vila Olímpica del  Vallbona              el Guinardó           el Coll
Codi_carrer                 331507                120104                134007                367402                337106
Nom_carrer                  Manuel Sanchis i Gua  Cordelles             Rector Oliveras       Jonqueres             Paral·lel / Comte Bo
Num_postal                  0079 0081             0668 0668             0263 0271             0168 0172             0661 0661
Descripcio_dia_setmana      Dijous                Dilluns               Diumenge              Dimecres              Dissabte
NK_Any                      2016                  2019                  2022                  2020                  2018
Mes_any                     8                     2                     3                     1                     9
Nom_mes                     Juny                  Desembre              Juliol                Maig                  Setembre
Dia_mes                     16                    31                    22                    9                     27
Hora_dia                    18                    2                     12                    22                    19
Descripcio_torn             Altres                Fallada mecànica o a  Avançament defectuós  Tarda                 Desobeir semàfor
Descripcio_causa_conductor  Nit                   Matí                  Tarda
Coordenada_UTM_X_ED50       427022.05             426761.7              429871.51             431670.89             430465.11
Coordenada_UTM_Y_ED50       4585564.71            4583090.74            4581512.15            4581252.84            4576286.04
Longitud                    2.18445249122226      2.15803155727034      2.184965659           2.1872159529804       2.16765671803296
Latitud                     41.4149058737121      41.409523017          41.388401032          41.3845059957384      41.427098953
Descripcio_causa_mediata    Desobeir altres seny  Manca precaució inco  No cedir la dreta     Avançament defectuós  Gir indegut o sense

A simple vista, ya encontramos que nuestro dataset contiene columnas que parecen dar el mismo tipo de información. En este caso, así como en los siguientes, lo que haremos será limitar el numero de columnas de manera que las que contienen la misma información se junten y se eliminen posteriormente.

En este dataset, en referencia a las coordenadas, hemos observado que existen diferentes sistemas de referencia (por ejemplo, el ED50) y que, además, pueden ser de diferentes tipos (por ejemplo, geográficas, UTM...). Sea el método que sea empleado, todas deberían ser equivalentes, ya que contienen el mismo tipo de información. (Fuente: https://www.ign.es/web/ca/calculadora-geodesica)

La idea, en este dataset, será comprobar si podemos rellenar la información de longitud y latitud con estos datos. De no ser, así decidiremos eliminar las columnas.

In [ ]:
filas_filtradas_Longitud = df_1.loc[df_1['Longitud'].isnull()&df_1['Coordenada_UTM_X_ED50'].notnull(),['Longitud','Coordenada_UTM_X_ED50']]
print(filas_filtradas_Longitud)

#hacemos lo mismo entre Latitud y la Coordenada_UTM_Y
filas_filtradas_Latitud = df_1.loc[df_1['Latitud'].isnull()&df_1['Coordenada_UTM_Y_ED50'].notnull(),['Latitud','Coordenada_UTM_Y_ED50']]
print(filas_filtradas_Latitud)

       Longitud  Coordenada_UTM_X_ED50
52129       NaN                   -1.0
52130       NaN                   -1.0
52131       NaN                   -1.0
52132       NaN                   -1.0
52133       NaN                   -1.0
52134       NaN                   -1.0
52135       NaN                   -1.0
53298       NaN                   -1.0
53299       NaN                   -1.0
54395       NaN                   -1.0
54396       NaN                   -1.0
54397       NaN                   -1.0
54398       NaN                   -1.0
55521       NaN                   -1.0
55522       NaN                   -1.0
55523       NaN                   -1.0
55524       NaN                   -1.0
55525       NaN                   -1.0
55526       NaN                   -1.0
56660       NaN                   -1.0
57819       NaN                   -1.0
57820       NaN                   -1.0
57821       NaN                   -1.0
57822       NaN                   -1.0
58944       NaN                   -1.0
58945       NaN                   -1.0
58946       NaN                   -1.0
58947       NaN                   -1.0
58948       NaN                   -1.0
58949       NaN                   -1.0
       Latitud  Coordenada_UTM_Y_ED50
52129      NaN                   -1.0
52130      NaN                   -1.0
52131      NaN                   -1.0
52132      NaN                   -1.0
52133      NaN                   -1.0
52134      NaN                   -1.0
52135      NaN                   -1.0
53298      NaN                   -1.0
53299      NaN                   -1.0
54395      NaN                   -1.0
54396      NaN                   -1.0
54397      NaN                   -1.0
54398      NaN                   -1.0
55521      NaN                   -1.0
55522      NaN                   -1.0
55523      NaN                   -1.0
55524      NaN                   -1.0
55525      NaN                   -1.0
55526      NaN                   -1.0
56660      NaN                   -1.0
57819      NaN                   -1.0
57820      NaN                   -1.0
57821      NaN                   -1.0
57822      NaN                   -1.0
58944      NaN                   -1.0
58945      NaN                   -1.0
58946      NaN                   -1.0
58947      NaN                   -1.0
58948      NaN                   -1.0
58949      NaN                   -1.0

Debido a que no podemos saber estos valores (ya que -1.0 no es un valor válido), decidimos eliminarlas de nuestro dataset.

De la misma manera, eliminaremos Nom_mes, ya que incluye la misma información que Mes_any. También renombraremos la columna NK_Any a Any, para tenerlo parecido a los demás datasets.

In [ ]:
# Eliminar las columnas especificadas
df_1.drop(columns=['Coordenada_UTM_X_ED50', 'Coordenada_UTM_Y_ED50','Nom_mes'], inplace=True)
df_1.rename(columns={'NK_Any': 'Any'}, inplace=True)

In [ ]:
df_1.isna().sum()

Numero_expedient                  0
Codi_districte                    0
Nom_districte                     0
Codi_barri                        0
Nom_barri                         0
Codi_carrer                       0
Nom_carrer                        1
Num_postal                       16
Descripcio_dia_setmana            0
Any                               0
Mes_any                           0
Dia_mes                           0
Hora_dia                          0
Descripcio_torn                   0
Descripcio_causa_conductor    18299
Longitud                         30
Latitud                          30
Descripcio_causa_mediata      51056
dtype: int64

#### *Dataframe* tipo 2

In [ ]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65271 entries, 0 to 65270
Data columns (total 36 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Numero_expedient           54720 non-null  object
 1   Codi_districte             65271 non-null  int64
 2   Nom_districte              65271 non-null  object
 3   Codi_barri                 65271 non-null  int64
 4   Nom_barri                  65271 non-null  object
 5   Codi_carrer                65271 non-null  int64
 6   Nom_carrer                 65269 non-null  object
 7   Num_postal_caption         49693 non-null  object
 8   Descripcio_dia_setmana     54720 non-null  object
 9   Dia_setmana                49377 non-null  object
 10  Descripcio_tipus_dia       38826 non-null  object
 11  Any                        32261 non-null  float64
 12  Mes_any                    54720 non-null  float64
 13  Nom_mes                    65271 non-null  object
 14  Dia_mes                    54720 non-null  float64
 15  Hora_dia                   54720 non-null  float64
 16  Descripcio_torn            54720 non-null  object
 17  Descripcio_tipus_accident  54720 non-null  object
 18  Coordenada_UTM_X           49377 non-null  object
 19  Coordenada_UTM_Y           49377 non-null  object
 20  Longitud                   57475 non-null  object
 21  Latitud                    57475 non-null  float64
 22  Codi_expedient             10551 non-null  object
 23  Num_postal                 10551 non-null  object
 24  ID_Dia_setmana             10551 non-null  object
 25  Tipus_dia                  10551 non-null  object
 26  Mes                        10551 non-null  float64
 27  Dia_de_mes                 10551 non-null  float64
 28  Hora_de_dia                10551 non-null  float64
 29  Torn                       10551 non-null  object
 30  Tipus_accident             10551 non-null  object
 31  NK_Any                     33010 non-null  float64
 32  Coordenada_UTM_X_ED50      15894 non-null  float64
 33  Coordenada_UTM_Y_ED50      15894 non-null  float64
 34  Longitud_WGS84             7794 non-null   float64
 35  Latitud_WGS84              7794 non-null   float64
dtypes: float64(13), int64(3), object(20)
memory usage: 17.9+ MB

In [ ]:
mostrar_valores_unicos_aleatorios_tabla(df_2)

Columna                    Valor 1               Valor 2               Valor 3               Valor 4               Valor 5
-------------------------  --------------------  --------------------  --------------------  --------------------  --------------------
Numero_expedient           2016S008049           2020S002807           2017S004774           2020S002633           2022S003000
Codi_districte             5                     1                     6                     9                     8
Nom_districte              Sarrià-Sant Gervasi   Gràcia                Nou Barris            Horta-Guinardó        Sant Martí
Codi_barri                 12                    32                    60                    54                    33
Nom_barri                  la Sagrera            el Camp de l'Arpa de  el Parc i la Llacuna  la Salut              la Prosperitat
Codi_carrer                78008                 120909                701564                134608                193006
Nom_carrer                 Aragó / Tarragona     Sant Bertran          Joaquín Maurín        Corts Catalanes / Ba  Castillejos / Valènc
Num_postal_caption         0242 0242             0009B0009B            0096 0096             19-55                 0219 0223
Descripcio_dia_setmana     Diumenge              Dissabte              Divendres             Dimarts               Dilluns
Dia_setmana                Diumenge              Ds                    Dm                    Dl                    Dijous
Descripcio_tipus_dia       Laboral
Any                        2016.0                2017.0                2018.0
Mes_any                    11.0                  10.0                  12.0                  9.0                   7.0
Nom_mes                    Gener                 Març                  Abril                 Juny                  Octubre
Dia_mes                    14.0                  20.0                  22.0                  13.0                  26.0
Hora_dia                   19.0                  12.0                  5.0                   2.0                   18.0
Descripcio_torn            Matí                  Tarda                 Nit
Descripcio_tipus_accident  Caiguda (dues rodes)  Col.lisió lateral     Sortida de via amb x  Altres                Bolcada (més de dues
Coordenada_UTM_X           429520.42             428559.4              429738.28             429061.79             427109.86
Coordenada_UTM_Y           4582415.71            4587798,8             4580532.32            4581986.85            4582751.18
Longitud                   2.142563              2.1832621528489       2.179102              2.183317              2.172434
Latitud                    41.400911             41.385429             41.38052              41.416875             41.38915351375601
Codi_expedient             2018S009807           2018S003108           2018S004698           2018S008368           2018S000507
Num_postal                 0742 0742             0320 0320             0194 0206             0423 0423             0029 0033
ID_Dia_setmana             Dg                    Ds                    Dl                    Dc                    Dm
Tipus_dia                  Laboral
Mes                        8.0                   6.0                   4.0                   2.0                   7.0
Dia_de_mes                 28.0                  7.0                   11.0                  30.0                  31.0
Hora_de_dia                11.0                  12.0                  3.0                   1.0                   9.0
Torn                       Nit                   Matí                  Tarda
Tipus_accident             Altres                Atropellament         Sortida de via amb x  Xoc contra element e  Col.lisió lateral
NK_Any                     2019.0                2020.0                2021.0                2022.0
Coordenada_UTM_X_ED50      430241.72             431053.31             429556.49             429554.29             430215.73
Coordenada_UTM_Y_ED50      4585227.59            4580319.43            4581024.14            4582364.06            4585444.3
Longitud_WGS84             2.15697905            2.177095807           2.162656461           2.170592827           2.143628864
Latitud_WGS84              41.378612721          41.396532696          41.383218483          41.398570705          41.447972278

Siguiendo el caso anterior, y con el objetivo de seguir eliminando duplicidades, lo que haremos es escoger aquellas columnas que contengan la misma información y complementarlas para, finalmente, eliminar una de las dos duplicadas. En este caso, se realizarán los siguientes cambios:

- 'Numero_expedient' = 'Codi_expedient'. Ambos refieren al número identificativo de cada uno de los expedientes

- Tipus_dia = 'Descripcio_tipus_dia'. Indica si el día de la semana en cuestión es laborable o no lo es.

- 'Mes_any' = 'Nom_mes'. Indica el mes del año

- Descripcio_dia_setmana' = 'ID_Dia_setmana' y 'Dia_setmana'. Se refiere al nombre del dia de la semana en que ocurrió el incidente

- 'Any' = 'NK Any'. Año en el que ocurrió el accidente.

- 'Dia_mes' = 'Dia_de_mes'. Dia del mes en el que ocurrió el accidente.

- 'Hora_dia' = 'Hora_de_dia'. Hora del día en el que ocurrió el accidente.

- 'Descripcio_torn' = 'Torn'. Momento del día en que se notificó y detalló el incidente (noche, día, tarde...)

- 'Descripcio_tipus_accident' = 'Tipus_accident'. Descripción del accidente

- 'Longitud' = 'Longitud_WGS84'

- 'Latitud' = 'Latitud_WGS84'

- 'Num_postal' ='Num_postal '


Una vez hechas estas combinaciones, se eliminarán las columnas extras (las que se encuentrán después del '=') y algunas otras que no aportan información.

In [ ]:
# Fusionar las columnas que son correspondientes
df_2['Numero_expedient'] = df_2['Numero_expedient'].combine_first(df_2['Codi_expedient'])

df_2['Tipus_dia'] = df_2['Tipus_dia'].combine_first(df_2['Descripcio_tipus_dia'])

df_2['Mes_any'] = df_2['Mes_any'].combine_first(df_2['Nom_mes'])

df_2['Descripcio_dia_setmana'] = df_2['Descripcio_dia_setmana'].combine_first(df_2['ID_Dia_setmana']).combine_first(df_2['Dia_setmana'])

df_2['Descripcio_tipus_dia'] = df_2['Descripcio_tipus_dia'].combine_first(df_2['Tipus_dia'])

df_2['Any'] = df_2['Any'].combine_first(df_2['NK_Any'])

df_2['Dia_mes'] = df_2['Dia_mes'].combine_first(df_2['Dia_de_mes'])

df_2['Hora_dia'] = df_2['Hora_dia'].combine_first(df_2['Hora_de_dia'])

df_2['Descripcio_torn'] = df_2['Descripcio_torn'].combine_first(df_2['Torn'])

df_2['Descripcio_tipus_accident'] = df_2['Descripcio_tipus_accident'].combine_first(df_2['Tipus_accident'])

df_2['Longitud'] = df_2['Longitud'].combine_first(df_2['Longitud_WGS84'])

df_2['Latitud'] = df_2['Latitud'].combine_first(df_2['Latitud_WGS84'])

df_2['Num_postal'] = df_2['Num_postal '].combine_first(df_2['Num_postal_caption'])

# Eliminar las columnas sobrantes
df_2.drop(columns=['Codi_expedient', 'Num_postal ','Num_postal_caption',
                   'Coordenada_UTM_X_ED50', 'Coordenada_UTM_Y_ED50', 'Dia_setmana',
                   'ID_Dia_setmana', 'Tipus_dia', 'NK_Any', 'Nom_mes', 'Dia_de_mes', 'Hora_de_dia',
                   'Torn', 'Tipus_accident', 'Longitud_WGS84', 'Latitud_WGS84',
                   'Coordenada_UTM_X', 'Coordenada_UTM_Y', 'Descripcio_tipus_dia','Mes', 'Num_postal'], inplace=True)

In [ ]:
# Diccionario para mapear nombres de meses a números
meses_dict = {
    'Gener': 1,
    'Febrer': 2,
    'Març': 3,
    'Abril': 4,
    'Maig': 5,
    'Juny': 6,
    'Juliol': 7,
    'Agost': 8,
    'Setembre': 9,
    'Octubre': 10,
    'Novembre': 11,
    'Desembre': 12
}

# Convertir los nombres de los meses a números usando el diccionario
df_2['Mes_any'] = df_2['Mes_any'].replace(meses_dict)

# Convertir columnas a tipos adecuados
df_2['Any'] = df_2['Any'].astype(int)  # Convertir 'Any' a tipo entero
df_2['Mes_any'] = df_2['Mes_any'].astype(int)
df_2['Dia_mes'] = df_2['Dia_mes'].astype(int)  # Convertir 'Dia_mes' a tipo entero
df_2['Hora_dia'] = df_2['Hora_dia'].astype(int)  # Convertir 'Hora_dia' a tipo entero

# Eliminar ';' si está presente en la columna 'Longitud'
df_2['Longitud'] = df_2['Longitud'].astype(str).str.replace(';', '')

# Limpiar los valores de 'Longitud' para eliminar los caracteres no numéricos
df_2.loc[df_2['Longitud'] == '2.1722741.', 'Longitud'] = '2.1722741'

df_2['Longitud'] = df_2['Longitud'].astype(float)
df_2['Latitud'] = df_2['Latitud'].astype(float)

In [ ]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65271 entries, 0 to 65270
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Numero_expedient           65271 non-null  object
 1   Codi_districte             65271 non-null  int64
 2   Nom_districte              65271 non-null  object
 3   Codi_barri                 65271 non-null  int64
 4   Nom_barri                  65271 non-null  object
 5   Codi_carrer                65271 non-null  int64
 6   Nom_carrer                 65269 non-null  object
 7   Descripcio_dia_setmana     65271 non-null  object
 8   Any                        65271 non-null  int64
 9   Mes_any                    65271 non-null  int64
 10  Dia_mes                    65271 non-null  int64
 11  Hora_dia                   65271 non-null  int64
 12  Descripcio_torn            65271 non-null  object
 13  Descripcio_tipus_accident  65271 non-null  object
 14  Longitud                   65269 non-null  float64
 15  Latitud                    65269 non-null  float64
dtypes: float64(2), int64(7), object(7)
memory usage: 8.0+ MB

In [ ]:
df_2.isna().sum()

Numero_expedient             0
Codi_districte               0
Nom_districte                0
Codi_barri                   0
Nom_barri                    0
Codi_carrer                  0
Nom_carrer                   2
Descripcio_dia_setmana       0
Any                          0
Mes_any                      0
Dia_mes                      0
Hora_dia                     0
Descripcio_torn              0
Descripcio_tipus_accident    0
Longitud                     2
Latitud                      2
dtype: int64

#### *Dataframe* tipo 3

In [ ]:
df_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62368 entries, 0 to 62367
Data columns (total 34 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Numero_expedient           62368 non-null  object
 1   Codi_districte             62368 non-null  int64
 2   Nom_districte              62368 non-null  object
 3   Codi_barri                 62368 non-null  object
 4   Nom_barri                  62368 non-null  object
 5   Codi_carrer                62368 non-null  int64
 6   Nom_carrer                 62366 non-null  object
 7   Num_postal                 20474 non-null  object
 8   Descripcio_dia_setmana     62368 non-null  object
 9   Dia_setmana                46710 non-null  object
 10  Descripcio_tipus_dia       46710 non-null  object
 11  Any                        30415 non-null  float64
 12  Mes_any                    62368 non-null  int64
 13  Nom_mes                    62368 non-null  object
 14  Dia_mes                    62368 non-null  int64
 15  Hora_dia                   62368 non-null  int64
 16  Descripcio_torn            62368 non-null  object
 17  Descripcio_causa_vianant   62368 non-null  object
 18  Numero_morts               62368 non-null  int64
 19  Numero_lesionats_lleus     62368 non-null  int64
 20  Numero_lesionats_greus     62368 non-null  int64
 21  Numero_victimes            62368 non-null  int64
 22  Numero_vehicles_implicats  62368 non-null  int64
 23  Coordenada_UTM_X           46710 non-null  object
 24  Coordenada_UTM_Y           46710 non-null  object
 25  Longitud                   54709 non-null  float64
 26  Latitud                    54709 non-null  float64
 27  Num_postal                 5138 non-null   object
 28  Num_postal_caption         31953 non-null  object
 29  NK_Any                     31953 non-null  float64
 30  Coordenada_UTM_X_ED50      15658 non-null  float64
 31  Coordenada_UTM_Y_ED50      15658 non-null  float64
 32  Longitud_WGS84             7635 non-null   float64
 33  Latitud_WGS84              7635 non-null   float64
dtypes: float64(8), int64(10), object(16)
memory usage: 16.2+ MB

In [ ]:
mostrar_valores_unicos_aleatorios_tabla(df_3)

Columna                    Valor 1               Valor 2               Valor 3               Valor 4               Valor 5
-------------------------  --------------------  --------------------  --------------------  --------------------  --------------------
Numero_expedient           2019S010013           2020S002400           2022S001263           2018S005376           2022S000824
Codi_districte             10                    7                     -1                    4                     5
Nom_districte              Ciutat Vella          Sant Andreu           Les Corts             Desconegut            Nou Barris
Codi_barri                 12                    72                    24-2-7                91-9-63               81-8-54
Nom_barri                  la Barceloneta        la Bordeta            la Teixonera          Vilapicina i la Torr  Canyelles
Codi_carrer                104505                209004                240300                194100                352653
Nom_carrer                 Balmes / Sant Gervas  Joan Miró / Doctor T  València / Passeig d  Taulat                Transversal 2
Num_postal                 0375 0375             0190 0192             0218 0220             0196 0196             0008 0010
Descripcio_dia_setmana     Divendres             Diumenge              Dissabte              Dimarts               Dijous
Dia_setmana                7                     Dm                    Dj                    Dv                    2
Descripcio_tipus_dia       Laboral
Any                        2016.0                2017.0                2018.0
Mes_any                    12                    10                    9                     11                    7
Nom_mes                    Agost                 Abril                 Setembre              Juliol                Març
Dia_mes                    5                     10                    21                    3                     20
Hora_dia                   9                     5                     3                     1                     6
Descripcio_torn            Tarda                 Matí                  Nit
Descripcio_causa_vianant   No és causa del  via  Transitar a peu per   Altres                Creuar per fora pas   Desobeir altres seny
Numero_morts               0                     1                     2
Numero_lesionats_lleus     1                     13                    10                    7                     12
Numero_lesionats_greus     0                     1                     2                     3                     4
Numero_victimes            14                    13                    26                    1                     2
Numero_vehicles_implicats  4                     3                     6                     9                     10
Coordenada_UTM_X           428084.31             431007,89             433333.32             431588.34             429381.68
Coordenada_UTM_Y           4584642,61            4583502.54            4582554.79            4584263.08            4585163,05
Longitud                   2.137914545274966     2.19190546            2.16499518            2.14573359            2.2050600759688503
Latitud                    41.42936527452704     41.4503226038734      41.3707534178831      41.3994452529128      41.4039972322539
Num_postal                 K58                   K99                   583                   154-156               244I
Num_postal_caption         0368C0368C            0276X0276X            0326 0326             0057 0059             920000
NK_Any                     2019.0                2020.0                2021.0                2022.0
Coordenada_UTM_X_ED50      427602.93             428518.54             433850.0              432279.35             431419.32
Coordenada_UTM_Y_ED50      4584867.54            4586622.48            4586271.24            4582926.6             4585601.9
Longitud_WGS84             2.186339504           2.153168637           2.201537576           2.195571523           2.150531906
Latitud_WGS84              41.423047507          41.444956358          41.383843479          41.395534486          41.381840288

Seguimos con el mismo proceso que en los dfs anteriores. Haremos los siguientes cambios:

- 'Any' = 'NK_Any'

- 'Longitud' = 'Longitud_WGS84'

- 'Latitud' = 'Latitud_WGS84'

- 'Num_postal' = 'Num_postal ' y 'Num_postal_caption'

El motivo de juntar la longitud y latitud con su respectivas escalas de 'WGS84'es debido a que contienen exactamente la misma información. Simplemente, lo único que cambia es la notación del nombre de la variable. Sin embargo, en ambas el sistema de referencia utilizado es el de *World Geodetic System 1984*, por lo que se incluye el mismo tipo de información. (Fuente: https://www.ayuware.es/blog/coordenadas-wgs84/)

In [ ]:
# Fusionar las columnas que son correspondientes
df_3['Any'] = df_3['Any'].combine_first(df_3['NK_Any'])

df_3['Longitud'] = df_3['Longitud'].combine_first(df_3['Longitud_WGS84'])

df_3['Latitud'] = df_3['Latitud'].combine_first(df_3['Latitud_WGS84'])

df_3['Num_postal']=df_3['Num_postal'].combine_first(df_3['Num_postal ']).combine_first(df_3['Num_postal_caption'])

# Eliminar las columnas sobrantes
df_3.drop(columns=['Num_postal ', 'Num_postal_caption','Nom_mes','Descripcio_tipus_dia',
                   'Coordenada_UTM_X_ED50', 'Coordenada_UTM_Y_ED50', 'Dia_setmana',
                   'Longitud_WGS84', 'Latitud_WGS84', 'NK_Any',
                   'Coordenada_UTM_X', 'Coordenada_UTM_Y'], inplace=True)

df_3['Any'] = df_3['Any'].astype(int)
# df_3['Codi_barri'] = df_3['Codi_barri'].astype(int)

In [ ]:
df_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62368 entries, 0 to 62367
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Numero_expedient           62368 non-null  object
 1   Codi_districte             62368 non-null  int64
 2   Nom_districte              62368 non-null  object
 3   Codi_barri                 62368 non-null  object
 4   Nom_barri                  62368 non-null  object
 5   Codi_carrer                62368 non-null  int64
 6   Nom_carrer                 62366 non-null  object
 7   Num_postal                 57565 non-null  object
 8   Descripcio_dia_setmana     62368 non-null  object
 9   Any                        62368 non-null  int64
 10  Mes_any                    62368 non-null  int64
 11  Dia_mes                    62368 non-null  int64
 12  Hora_dia                   62368 non-null  int64
 13  Descripcio_torn            62368 non-null  object
 14  Descripcio_causa_vianant   62368 non-null  object
 15  Numero_morts               62368 non-null  int64
 16  Numero_lesionats_lleus     62368 non-null  int64
 17  Numero_lesionats_greus     62368 non-null  int64
 18  Numero_victimes            62368 non-null  int64
 19  Numero_vehicles_implicats  62368 non-null  int64
 20  Longitud                   62344 non-null  float64
 21  Latitud                    62344 non-null  float64
dtypes: float64(2), int64(11), object(9)
memory usage: 10.5+ MB

In [ ]:
df_3.isna().sum()

Numero_expedient                0
Codi_districte                  0
Nom_districte                   0
Codi_barri                      0
Nom_barri                       0
Codi_carrer                     0
Nom_carrer                      2
Num_postal                   4803
Descripcio_dia_setmana          0
Any                             0
Mes_any                         0
Dia_mes                         0
Hora_dia                        0
Descripcio_torn                 0
Descripcio_causa_vianant        0
Numero_morts                    0
Numero_lesionats_lleus          0
Numero_lesionats_greus          0
Numero_victimes                 0
Numero_vehicles_implicats       0
Longitud                       24
Latitud                        24
dtype: int64

#### *Dataframe* tipo 4

In [ ]:
df_4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118274 entries, 0 to 118273
Data columns (total 37 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Codi_expedient            58283 non-null   object
 1   Codi_districte            118274 non-null  int64
 2   Nom_districte             118274 non-null  object
 3   Codi_barri                118274 non-null  int64
 4   Nom_barri                 118274 non-null  object
 5   Codi_carrer               118274 non-null  int64
 6   Nom_carrer                118217 non-null  object
 7   Num_postal                65427 non-null   object
 8   Descripcio_dia_setmana    118274 non-null  object
 9   Dia_setmana               89020 non-null   object
 10  Descripcio_tipus_dia      89020 non-null   object
 11  Any                       58284 non-null   float64
 12  Mes_any                   118274 non-null  int64
 13  Nom_mes                   118274 non-null  object
 14  Dia_mes                   118274 non-null  int64
 15  Hora_dia                  118274 non-null  int64
 16  Descripcio_causa_vianant  118274 non-null  object
 17  Descripcio_tipus_vehicle  118251 non-null  object
 18  Descripcio_model          118247 non-null  object
 19  Descripcio_marca          118251 non-null  object
 20  Descripcio_color          118251 non-null  object
 21  Descripcio_carnet         118251 non-null  object
 22  Antiguitat_carnet         118251 non-null  object
 23  Coordenada_UTM_X          89013 non-null   object
 24  Coordenada_UTM_Y          89013 non-null   object
 25   Longitud                 19410 non-null   float64
 26   Latitud                  19410 non-null   float64
 27  Num_postal                24906 non-null   object
 28  Longitud                  84501 non-null   object
 29  Latitud                   84501 non-null   object
 30  Descripcio_torn           78913 non-null   object
 31  Numero_expedient          59968 non-null   object
 32  NK_Any                    59990 non-null   float64
 33  Coordenada_UTM_X_ED50     29239 non-null   float64
 34  Coordenada_UTM_Y_ED50     29239 non-null   float64
 35  Longitud_WGS84            14297 non-null   float64
 36  Latitud_WGS84             14297 non-null   float64
dtypes: float64(8), int64(6), object(23)
memory usage: 33.4+ MB

In [ ]:
mostrar_valores_unicos_aleatorios_tabla(df_4)

Columna                   Valor 1               Valor 2               Valor 3               Valor 4              Valor 5
------------------------  --------------------  --------------------  --------------------  -------------------  --------------------
Codi_expedient            2017S004488           2016S000453           2016S001197           2017S010095          2016S005466
Codi_districte            6                     7                     2                     5                    9
Nom_districte             Horta-Guinardó        Sarrià-Sant Gervasi   Gràcia                Sants-Montjuïc       Nou Barris
Codi_barri                6                     59                    37                    44                   10
Nom_barri                 Vallbona              la Sagrera            Ciutat Meridiana      Sant Andreu          el Poble-sec
Codi_carrer               63850                 277208                102805                311703               700060
Nom_carrer                Balmes / Provença     Cànoves               Gràcia / Gran de Grà  Casanova / Rosselló  Garrofers / Escultor
Num_postal                60-62                 0014 0014             000330000             0292 0292            0388V0388V
Descripcio_dia_setmana    Dissabte              Dimarts               Dimecres              Divendres            Dilluns
Dia_setmana               Dv                    Dm                    Ds                    Dj                   Dc
Descripcio_tipus_dia      Laboral
Any                       2016.0                2017.0                2018.0
Mes_any                   3                     11                    1                     7                    5
Nom_mes                   Gener                 Abril                 Novembre              Desembre             Octubre
Dia_mes                   29                    25                    26                    24                   30
Hora_dia                  14                    13                    1                     10                   9
Descripcio_causa_vianant  No és causa del  via  Desobeir el senyal d  Transitar a peu per   Altres               Desobeir altres seny
Descripcio_tipus_vehicle  Altres vehicles sens  Altres vehicles amb   Cuadriciclo <75cc     Autocaravana         Tren o tramvia
Descripcio_model          XL833L                DINK 125              VITALITY              LIONS CITY E4        PRIMERA 1.6
Descripcio_marca          MAC CORMICK           CARROCERIAS SANCA SA  GOES                  BMW                  NISSAN
Descripcio_color          Gris                  Verd                  Blau                  Platejat             Negre/Groc
Descripcio_carnet         D                     E C1                  C1                    Sense permís         A
Antiguitat_carnet         37                    66                    45                    68                   67
Coordenada_UTM_X          431062.98             427750,96             429571.02             430456,1             432281,34
Coordenada_UTM_Y          4584452.37            4582109.55            4583583,6             4584920.32           4579010,16
Longitud                  2.200424              2.213404              2.194666              2.148819             2.162072
Latitud                   41.423634             41.39653              41.401525             41.390144            41.445332
Num_postal                649-651               20600000              36                    0057B0057B           K100
Longitud                  2.1178926784916308    2.198844              2.136254              2.1404279771927768   2.158787
Latitud                   41.39997618873851     41.40362898223898     41.40287013922813     41.38006571925929    41.370622
Descripcio_torn           Nit                   Matí                  Tarda
Numero_expedient          2019S002730           2019S007508           2021S007075           2020S004041          2020S000613
NK_Any                    2019.0                2020.0                2021.0                2022.0
Coordenada_UTM_X_ED50     433943.46             429334.44             430165.02             429750.44            429554.17
Coordenada_UTM_Y_ED50     4583926.42            4581994.16            4584775.53            4583840.45           4581013.64
Longitud_WGS84            2.130734178           2.143850075           2.187221954           2.185527994          2.116327395
Latitud_WGS84             41.397581875          41.367084428          41.397937106          41.388028681         41.389103337

Aquí realizaremos los siguientes cambios:

- 'Codi_expedient' = 'Numero_expedient'. Ambos se refieren al número identificatibvo único de cada uno de los expedientes abiertos sobre los accidentes

- 'Num_postal' = 'Num_postal '

- 'Any' = 'NK_Any'

- Descripcio_dia_setmana = Dia_setmana

- 'Coordenada_UTM_X' = 'Coordenada_UTM_X_ED50'

- 'Coordenada_UTM_Y' = 'Coordenada_UTM_Y_ED50'

- 'Longitud' = 'Longitud_WGS84'

- 'Latitud' = 'Latitud_WGS84'

In [ ]:
# Fusionamos Numero_expedient con Codi_expedient
df_4['Numero_expedient'] = df_4['Numero_expedient'].combine_first(df_4['Codi_expedient'])
#en este caso queremos que numero_expedient sea la primera columna del df (queremos igualarlo a los demás dfs)
# Una vez juntas, eliminamos la columna 'Codi_expedient'
df_4.drop(columns='Codi_expedient', inplace=True)

#Fusionamos Num_postal con Num_postal y eliminamos Num_postal
df_4['Num_postal'] = df_4['Num_postal'].combine_first(df_4['Num_postal '])
df_4.drop(columns='Num_postal ', inplace=True)

#Fusionamos Any con NK_Any y eliminamos NK_Any
df_4['Any']=df_4['Any'].combine_first(df_4['NK_Any'])
df_4.drop(columns='NK_Any',inplace=True)

#Fusionamos Descripcio_dia_setmana con Dia_setmana y eliminamos Descripcio_dia_setmana
df_4['Descripcio_dia_setmana']=df_4['Descripcio_dia_setmana'].combine_first(df_4['Dia_setmana'])
df_4.drop(columns='Dia_setmana',inplace=True)

#Fusionamos Coordenada_UTM_X con Coordenada_UTM_X_ED50 y eliminamos Coordenada_UTM_X_ED50
df_4['Coordenada_UTM_X']=df_4['Coordenada_UTM_X'].combine_first(df_4['Coordenada_UTM_X_ED50'])
df_4.drop(columns='Coordenada_UTM_X_ED50',inplace=True)

#Fusionamos Coordenada_UTM_Y con Coordenada_UTM_Y_ED50 y eliminamos Coordenada_UTM_Y_ED50
df_4['Coordenada_UTM_Y']=df_4['Coordenada_UTM_Y'].combine_first(df_4['Coordenada_UTM_Y_ED50'])
df_4.drop(columns='Coordenada_UTM_Y_ED50',inplace=True)

#Fusionamos Longitud con Longitud_WGS84 y eliminamos Longitud_WGS84
df_4[' Longitud']=df_4[' Longitud'].combine_first(df_4['Longitud_WGS84'])
df_4.drop(columns='Longitud_WGS84',inplace=True)

#Fusionamos Latitud con Latitud_WGS84 y eliminamos Latitud_WGS84
df_4[' Latitud']=df_4[' Latitud'].combine_first(df_4['Latitud_WGS84'])
df_4.drop(columns='Latitud_WGS84',inplace=True)

#Fusionamos Longitud con ' Longitud' y eliminamos ' Longitud'
df_4['Longitud']=df_4['Longitud'].combine_first(df_4[' Longitud'])
df_4.drop(columns=' Longitud',inplace=True)

#Fusionamos Latitud con ' Latitud' y eliminamos ' Latitud'
df_4['Latitud']=df_4['Latitud'].combine_first(df_4[' Latitud'])
df_4.drop(columns=' Latitud',inplace=True)

#Convertimos las variables al tipo correcto
df_4['Any'] = df_4['Any'].astype(int)

df_4['Latitud'] = df_4['Latitud'].astype(str)
df_4['Longitud'] = df_4['Longitud'].astype(str)

# Reemplazar los valores de la columna 'Latitud' que son simplemente un string vacío por -1
df_4.loc[df_4['Latitud'] == "'", 'Latitud'] = -1
df_4.loc[df_4['Longitud'] == "'", 'Longitud'] = -1

df_4['Longitud'] = df_4['Longitud'].astype(float)
df_4['Latitud'] = df_4['Latitud'].astype(float)

Tratamos de reorganizar el df para que Numero_expedient aparezca el primero. Igual que en los casos anteriores, hemos comprobado que las columnas 'Coordenada_UTM_X' y 'Coordenada_UTM_Y' no nos pueden ser útiles para los valores NaN que existen en las columnas de Longitud y Latitud, respectivamente. Por ende, decidimos eliminarlas. Además, eliminamos las siguientes columnas que no son necesarias ya que, aquellas que incluyen la misma información, no tienen nulos. Finalmente, también eliminamos, los valores NaN de Numero_expedient, ya que nos resultará imposible encontrar los valores.

In [ ]:
ultima_columna = df_4.columns[-1]

# Creamos una lista con los nombres de las columnas, excluyendo la última
nombres_columnas = list(df_4.columns[:-1])

# Insertamos el nombre de la última columna en la primera posición
nombres_columnas.insert(0, ultima_columna)

# Reordenamos las columnas según la nueva lista de nombres de columnas
df_4 = df_4[nombres_columnas]

#eliminamos las columnas

df_4.drop(columns=['Coordenada_UTM_X','Coordenada_UTM_Y'], inplace=True)

df_4.drop(columns=['Descripcio_tipus_dia','Nom_mes'],inplace=True)

df_4.dropna(subset=['Numero_expedient'], inplace=True)

# Convertir al tipo correcto
df_4.loc[df_4['Antiguitat_carnet'] == "Desconegut", 'Antiguitat_carnet'] = -1
df_4['Antiguitat_carnet'] = df_4['Antiguitat_carnet'].astype(int)

<ipython-input-26-88dc9aae46ce>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_4.drop(columns=['Coordenada_UTM_X','Coordenada_UTM_Y'], inplace=True)
<ipython-input-26-88dc9aae46ce>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_4.drop(columns=['Descripcio_tipus_dia','Nom_mes'],inplace=True)
<ipython-input-26-88dc9aae46ce>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_4.dropna(subset=['Numero_expedient'], inplace=True)
<ipython-input-26-88dc9aae46ce>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_4['Antiguitat_carnet'] = df_4['Antiguitat_carnet'].astype(int)

In [ ]:
df_4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 118251 entries, 0 to 118273
Data columns (total 23 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Numero_expedient          118251 non-null  object
 1   Codi_districte            118251 non-null  int64
 2   Nom_districte             118251 non-null  object
 3   Codi_barri                118251 non-null  int64
 4   Nom_barri                 118251 non-null  object
 5   Codi_carrer               118251 non-null  int64
 6   Nom_carrer                118195 non-null  object
 7   Num_postal                90312 non-null   object
 8   Descripcio_dia_setmana    118251 non-null  object
 9   Any                       118251 non-null  int64
 10  Mes_any                   118251 non-null  int64
 11  Dia_mes                   118251 non-null  int64
 12  Hora_dia                  118251 non-null  int64
 13  Descripcio_causa_vianant  118251 non-null  object
 14  Descripcio_tipus_vehicle  118251 non-null  object
 15  Descripcio_model          118247 non-null  object
 16  Descripcio_marca          118251 non-null  object
 17  Descripcio_color          118251 non-null  object
 18  Descripcio_carnet         118251 non-null  object
 19  Antiguitat_carnet         118251 non-null  int64
 20  Longitud                  118185 non-null  float64
 21  Latitud                   118185 non-null  float64
 22  Descripcio_torn           78892 non-null   object
dtypes: float64(2), int64(8), object(13)
memory usage: 21.7+ MB

In [ ]:
df_4.isna().sum()

Numero_expedient                0
Codi_districte                  0
Nom_districte                   0
Codi_barri                      0
Nom_barri                       0
Codi_carrer                     0
Nom_carrer                     56
Num_postal                  27939
Descripcio_dia_setmana          0
Any                             0
Mes_any                         0
Dia_mes                         0
Hora_dia                        0
Descripcio_causa_vianant        0
Descripcio_tipus_vehicle        0
Descripcio_model                4
Descripcio_marca                0
Descripcio_color                0
Descripcio_carnet               0
Antiguitat_carnet               0
Longitud                       66
Latitud                        66
Descripcio_torn             39359
dtype: int64

#### *Dataframe* tipo 5

In [ ]:
df_5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62357 entries, 0 to 62356
Data columns (total 39 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Numero_expedient          52014 non-null  object
 1   Codi_districte            62357 non-null  int64
 2   Nom_districte             62357 non-null  object
 3   Codi_barri                62357 non-null  int64
 4   Nom_barri                 62357 non-null  object
 5   Codi_carrer               62357 non-null  int64
 6   Nom_carrer                62356 non-null  object
 7   Num_postal                10153 non-null  object
 8   Descripcio_dia_setmana    52014 non-null  object
 9   Dia_setmana               46715 non-null  object
 10  Descripcio_tipus_dia      36372 non-null  object
 11  Any                       20083 non-null  float64
 12  Mes_any                   52014 non-null  float64
 13  Nom_mes                   62357 non-null  object
 14  Dia_mes                   52014 non-null  float64
 15  Hora_dia                  52014 non-null  float64
 16  Descripcio_torn           52014 non-null  object
 17  Descripcio_causa_mediata  52014 non-null  object
 18  Coordenada_UTM_X          36372 non-null  object
 19  Coordenada_UTM_Y          36372 non-null  object
 20  Longitud                  54704 non-null  float64
 21  Latitud                   54704 non-null  float64
 22  Número_d'expedient        10343 non-null  object
 23  Num_postal                47404 non-null  object
 24  Descripció_dia_setmana    10343 non-null  object
 25  Descripció_tipus_dia      10343 non-null  object
 26  NK Any                    10343 non-null  float64
 27  Mes_de_any                10343 non-null  float64
 28  Dia_de_mes                10343 non-null  float64
 29  Hora_de_dia               10343 non-null  float64
 30  Descripció_torn           10343 non-null  object
 31  Descripció_causa_mediata  10343 non-null  object
 32  Coordenada_UTM_(X)        10343 non-null  float64
 33  Coordenada_UTM_(Y)        10343 non-null  float64
 34  NK_Any                    31931 non-null  float64
 35  Coordenada_UTM_X_ED50     15642 non-null  float64
 36  Coordenada_UTM_Y_ED50     15642 non-null  float64
 37  Longitud_WGS84            7630 non-null   float64
 38  Latitud_WGS84             7630 non-null   float64
dtypes: float64(17), int64(3), object(19)
memory usage: 18.6+ MB

In [ ]:
mostrar_valores_unicos_aleatorios_tabla(df_5)

Columna                   Valor 1               Valor 2               Valor 3               Valor 4               Valor 5
------------------------  --------------------  --------------------  --------------------  --------------------  --------------------
Numero_expedient          2016S000037           2016S008733           2019S002419           2020S002502           2019S003640
Codi_districte            1                     7                     -1                    4                     9
Nom_districte             Les Corts             Nou Barris            Sants-Montjuïc        Gràcia                Sarrià-Sant Gervasi
Codi_barri                68                    49                    8                     13                    2
Nom_barri                 el Fort Pienc         el Besòs i el Maresm  Sarrià                Pedralbes             el Raval
Codi_carrer               138201                365000                701357                201807                197700
Nom_carrer                AV DIAGONAL           Provença / Aribau     Hipòlit Lázaro / Rom  Rambla / Boqueria     Litoral (Llobregat)
Num_postal                0134B0134B            9999 9999             0020 0020             0037 0037             0539 0541
Descripcio_dia_setmana    Divendres             Dissabte              Dijous                Diumenge              Dilluns
Dia_setmana               Dg                    Dj                    Dv                    Dc                    Ds
Descripcio_tipus_dia      Laboral
Any                       2016.0                2018.0
Mes_any                   3.0                   9.0                   4.0                   7.0                   2.0
Nom_mes                   Febrer                Agost                 Juny                  Octubre               Gener
Dia_mes                   20.0                  14.0                  15.0                  25.0                  31.0
Hora_dia                  4.0                   2.0                   19.0                  20.0                  0.0
Descripcio_torn           Matí                  Tarda                 Nit
Descripcio_causa_mediata  Objectes o animals a  Calçada en mal estat  Estat de la senyalit  Alcoholèmia           Factors meteorològic
Coordenada_UTM_X          433272.5              431626.17             431749.15             427612,23             429187.03
Coordenada_UTM_Y          4584930.17            4583311,72            4582346,79            4584181.6             4587872,79
Longitud                  2.16376               2.168223              2.187302              2.144532              2.190955
Latitud                   41.402447             41.394793             41.43285              41.382763             41.39871151279188
Número_d'expedient        2017S001209           2017S006664           2017S000367           2017S001635           2017S000180
Num_postal                000860000             0055 0055             0064S0064S            0128 0140             0092B0092B
Descripció_dia_setmana    Dilluns               Dimecres              Dimarts               Diumenge              Divendres
Descripció_tipus_dia      Laboral
NK Any                    2017.0
Mes_de_any                2.0                   7.0                   5.0                   10.0                  6.0
Dia_de_mes                30.0                  2.0                   16.0                  8.0                   15.0
Hora_de_dia               19.0                  17.0                  13.0                  6.0                   10.0
Descripció_torn           Tarda                 Matí                  Nit
Descripció_causa_mediata  Factors meteorològic  Alcoholèmia           Excés de velocitat o  Calçada en mal estat  Drogues o medicament
Coordenada_UTM_(X)        430861.6              428838.56             430705.84             431418.19             428387.67
Coordenada_UTM_(Y)        4586781.61            4582727.45            4591124.95            4588272.86            4581526.43
NK_Any                    2019.0                2020.0                2021.0                2022.0
Coordenada_UTM_X_ED50     430529.8              431330.27             429167.96             430315.65             431116.21
Coordenada_UTM_Y_ED50     4583208.29            4587684.07            4583574.35            4581907.04            4579173.07
Longitud_WGS84            2.128153264           2.164591496           2.118690491           2.177100496           2.213762967
Latitud_WGS84             41.43251365           41.448565879          41.375008261          41.382217027          41.418606808

En este caso, de las 39 columnas, detectamos que hay muchas que siguen dando información duplicada. Con el mismo objetivo que en los casos anteriores, deseamos unir las columnas que tratan la misma información. En concreto, igualaremos la siguientes columnas:

- 'Numero_expedient' = 'Número_d'expedient'. Ambos refieren al número identificativo de cada uno de los expedientes

- 'Num_postal' ='Num_postal '

- Descripcio_dia_setmana' = 'Descripció_dia_setmana'. Se refiere al nombre del dia de la semana en que ocurrió el incidente

- Descripcio_tipus_dia = 'Descripció_tipus_dia'

- 'Any' = 'NK Any','NK_Any'

- 'Mes_any' = 'Mes_de_any'

- 'Dia_mes' = 'Dia_de_mes'

- 'Hora_dia' = 'Hora_de_dia'

- 'Descripcio_torn' = 'Descripció_torn'

- 'Descripcio_causa_mediata' = 'Descripció_causa_mediata'

- 'Coordenada_UTM_X'= 'Coordenada_UTM_(X)', 'Coordenads_UTM_X_ED50

- 'Coordenada_UTM_Y' = 'Coordenada_UTM_(Y)','Coordenada_UTM_Y_ED50

- 'Longitud' = 'Longitud_WGS84'

- 'Latitud' = 'Latitud_WGS84'

In [ ]:
#Fusionamos Numero_expedient con Número_d'expedient y eliminamos Número_d'expedient
df_5['Numero_expedient'] = df_5['Numero_expedient'].combine_first(df_5["Número_d'expedient"])
df_5.drop(columns="Número_d'expedient", inplace=True)

#Fusionamos Num_postal con Num_postal  y eliminamos Num_postal
df_5['Num_postal']=df_5['Num_postal'].combine_first(df_5['Num_postal '])
df_5.drop(columns='Num_postal ',inplace=True)

#Fusionamos Descripcio_dia_setmana con Descripció_dia_setmana y eliminamos Descripció_dia_setmana
df_5['Descripcio_dia_setmana']=df_5['Descripcio_dia_setmana'].combine_first(df_5['Descripció_dia_setmana'])
df_5.drop(columns='Descripció_dia_setmana',inplace=True)

#Fusionamos Descripcio_tipus_dia con Descripció_tipus_dia y eliminamos Descripció_tipus_dia
df_5['Descripcio_tipus_dia']=df_5['Descripcio_tipus_dia'].combine_first(df_5['Descripció_tipus_dia'])
df_5.drop(columns='Descripció_tipus_dia',inplace=True)

#Fusionamos Any con NK Any y NK_Any y eliminamos NK Any y NK_Any
df_5['Any']=df_5['Any'].combine_first(df_5['NK Any']).combine_first(df_5['NK_Any'])
df_5.drop(columns=['NK Any','NK_Any'],inplace=True)

#Fusionamos Mes_any con Mes_de_any y eliminamos Mes_de_any
df_5['Mes_any']=df_5['Mes_any'].combine_first(df_5['Mes_de_any'])
df_5.drop(columns=['Mes_de_any'],inplace=True)

#Fusionamos Dia_mes con Dia_de_mes y eliminamos Dia_de_mes
df_5['Dia_mes']=df_5['Dia_mes'].combine_first(df_5['Dia_de_mes'])
df_5.drop(columns=['Dia_de_mes'],inplace=True)

#Fusionamos Hora_dia con Hora_de_dia y eliminamos Hora_de_dia
df_5['Hora_dia']=df_5['Hora_dia'].combine_first(df_5['Hora_de_dia'])
df_5.drop(columns=['Hora_de_dia'],inplace=True)

#Fusionamos Descripcio_torn con Descripció_torn y eliminamos Descripció_torn
df_5['Descripcio_torn']=df_5['Descripcio_torn'].combine_first(df_5['Descripció_torn'])
df_5.drop(columns=['Descripció_torn'],inplace=True)

#Fusionamos Descripcio_causa_mediata con Descripció_causa_mediata y eliminamos Descripció_causa_mediata
df_5['Descripcio_causa_mediata']=df_5['Descripcio_causa_mediata'].combine_first(df_5['Descripció_causa_mediata'])
df_5.drop(columns=['Descripció_causa_mediata'],inplace=True)

#Fusionamos Coordenada_UTM_X con Coordenada_UTM_(X) y Coordenada_UTM_X_ED50 y eliminamos Coordenada_UTM_(X) y Coordenada_UTM_X_ED50
df_5['Coordenada_UTM_X']=df_5['Coordenada_UTM_X'].combine_first(df_5['Coordenada_UTM_(X)']).combine_first(df_5['Coordenada_UTM_X_ED50'])
df_5.drop(columns=['Coordenada_UTM_(X)','Coordenada_UTM_X_ED50'],inplace=True)

#Fusionamos Coordenada_UTM_Y con Coordenada_UTM_(Y) y Coordenada_UTM_Y_ED50 y eliminamos Coordenada_UTM_(Y) y Coordenada_UTM_Y_ED50
df_5['Coordenada_UTM_Y']=df_5['Coordenada_UTM_Y'].combine_first(df_5['Coordenada_UTM_(Y)']).combine_first(df_5['Coordenada_UTM_Y_ED50'])
df_5.drop(columns=['Coordenada_UTM_(Y)','Coordenada_UTM_Y_ED50'],inplace=True)

#Fusionamos Longitud con Longitud_WGS84 y eliminamos Longitud_WGS84
df_5['Longitud']=df_5['Longitud'].combine_first(df_5['Longitud_WGS84'])
df_5.drop(columns=['Longitud_WGS84'],inplace=True)

#Fusionamos Latitud con Latitud_WGS84 y eliminamos Latitud_WGS84
df_5['Latitud']=df_5['Latitud'].combine_first(df_5['Latitud_WGS84'])
df_5.drop(columns=['Latitud_WGS84'],inplace=True)

# Convertir columnas a tipos adecuados
df_5['Any'] = df_5['Any'].astype(int)  # Convertir 'Any' a tipo entero
df_5['Mes_any'] = df_5['Mes_any'].astype(int)
df_5['Dia_mes'] = df_5['Dia_mes'].astype(int)  # Convertir 'Dia_mes' a tipo entero
df_5['Hora_dia'] = df_5['Hora_dia'].astype(int)  # Convertir 'Hora_dia' a tipo entero

Antes de seguir eliminando columnas duplicadas, intentaremos ver si podemos rellenar los NaNs con las existentes.

En principio, nos gustaría mantener las columnas de Longitud y Latitud, y eliminar las Coordenadas_UTM_X y las Coordenadas_UTM_Y. Sin embargo, debido a la presencia de NaNs en las columnas de Longitud y Latitud, miraremos primero si podemos quitar esos NaNs reemplazándolos con los valores de las coordenadas UTM

Como, en ambos casos, no podemos reemplazar ningún valor nulo, decidimos eliminar las columnas de Coordenada_UTM_X y de Coordenada_UTM_Y. Además, eliminamos las siguientes columnas que no son necesarias ya que, aquellas que incluyen la misma información, no tienen nulos.

In [ ]:
#decidimos eliminar las columnas
df_5.drop(columns=['Coordenada_UTM_X','Coordenada_UTM_Y', 'Dia_setmana','Descripcio_tipus_dia','Nom_mes'],inplace=True)

In [ ]:
df_5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62357 entries, 0 to 62356
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Numero_expedient          62357 non-null  object
 1   Codi_districte            62357 non-null  int64
 2   Nom_districte             62357 non-null  object
 3   Codi_barri                62357 non-null  int64
 4   Nom_barri                 62357 non-null  object
 5   Codi_carrer               62357 non-null  int64
 6   Nom_carrer                62356 non-null  object
 7   Num_postal                57557 non-null  object
 8   Descripcio_dia_setmana    62357 non-null  object
 9   Any                       62357 non-null  int64
 10  Mes_any                   62357 non-null  int64
 11  Dia_mes                   62357 non-null  int64
 12  Hora_dia                  62357 non-null  int64
 13  Descripcio_torn           62357 non-null  object
 14  Descripcio_causa_mediata  62357 non-null  object
 15  Longitud                  62334 non-null  float64
 16  Latitud                   62334 non-null  float64
dtypes: float64(2), int64(7), object(8)
memory usage: 8.1+ MB

In [ ]:
#observamos valores nulos
df_5.isna().sum()

Numero_expedient               0
Codi_districte                 0
Nom_districte                  0
Codi_barri                     0
Nom_barri                      0
Codi_carrer                    0
Nom_carrer                     1
Num_postal                  4800
Descripcio_dia_setmana         0
Any                            0
Mes_any                        0
Dia_mes                        0
Hora_dia                       0
Descripcio_torn                0
Descripcio_causa_mediata       0
Longitud                      23
Latitud                       23
dtype: int64

#### *Dataframe* tipo 6

In [ ]:
df_6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79647 entries, 0 to 79646
Data columns (total 46 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Numero_expedient                          45139 non-null  object
 1   Codi_districte                            79647 non-null  int64
 2   Nom_districte                             79647 non-null  object
 3   Codi_barri                                79647 non-null  int64
 4   Nom_barri                                 79647 non-null  object
 5   Codi_carrer                               79647 non-null  int64
 6   Nom_carrer                                74359 non-null  object
 7   Num_postal                                28798 non-null  object
 8   Descripcio_dia_setmana                    79647 non-null  object
 9   Dia_setmana                               61728 non-null  object
 10  Descripcio_tipus_dia                      61728 non-null  object
 11  Any                                       36074 non-null  float64
 12  Mes_any                                   12072 non-null  float64
 13  Nom_mes                                   79647 non-null  object
 14  Dia_mes                                   79647 non-null  int64
 15  Descripcio_torn                           79647 non-null  object
 16  Hora_dia                                  79647 non-null  int64
 17  Descripcio_causa_vianant                  79647 non-null  object
 18  Desc_Tipus_vehicle_implicat               79647 non-null  object
 19  Descripcio_sexe                           56983 non-null  object
 20  Edat                                      79647 non-null  object
 21  Descripcio_tipus_persona                  56983 non-null  object
 22  Descripcio_situacio                       36074 non-null  object
 23  Descripcio_victimitzacio                  79647 non-null  object
 24  Coordenada_UTM_X                          61711 non-null  object
 25  Coordenada_UTM_Y                          61711 non-null  object
 26  Longitud                                  70700 non-null  object
 27  Latitud                                   70700 non-null  object
 28  Mes_ any                                  67575 non-null  float64
 29  Numero_Expedient                          34508 non-null  object
 30  Num_postal                                43573 non-null  object
 31  NK_ Any                                   43573 non-null  float64
 32  Descripcio_Lloc_atropellament_vianat      34508 non-null  object
 33  Descripcio_Motiu_desplaçament_vianant     20909 non-null  object
 34  Descripcio_Motiu_desplaçament_conductor   20909 non-null  object
 35  Descripció_sexe                           22664 non-null  object
 36  Descripció_tipus_persona                  22664 non-null  object
 37  Descripcio_Motiu_desplaĂ§ament_vianant    13810 non-null  object
 38  Descripcio_Motiu_desplaĂ§ament_conductor  13810 non-null  object
 39  Descripcio_Motiu_desplaÃ§ament_vianant    8854 non-null   object
 40  Descripcio_Motiu_desplaÃ§ament_conductor  8854 non-null   object
 41  Coordenada_UTM_X_ED50                     17919 non-null  object
 42  Coordenada_UTM_Y_ED50                     17919 non-null  object
 43  Longitud_WGS84                            8825 non-null   float64
 44  Latitud_WGS84                             8825 non-null   float64
 45  Descripcio_Lloc_atropellament_vianant     9065 non-null   object
dtypes: float64(6), int64(5), object(35)
memory usage: 28.0+ MB

In [ ]:
mostrar_valores_unicos_aleatorios_tabla(df_6)

Columna                                   Valor 1               Valor 2               Valor 3               Valor 4               Valor 5
----------------------------------------  --------------------  --------------------  --------------------  --------------------  --------------------
Numero_expedient                          2022S003626           2022S004435           2018S003474           2017S005802           2016S001976
Codi_districte                            -1                    6                     2                     9                     7
Nom_districte                             Eixample              Gràcia                Sarrià-Sant Gervasi   Sarriŕ-Sant Gervasi   Desconegut
Codi_barri                                73                    42                    -1                    65                    50
Nom_barri                                 Hostafrancs           la Marina de Port     Can Baró              Sant Gervasi - Galva  Vallvidrera, el Tibi
Codi_carrer                               171808                148602                245201                157400                18006
Nom_carrer                                Maria Aurèlia Capman  Pere II de Montcada   Ciències              Marina / Salvador Es  Corts / Vilamur
Num_postal                                57                    0327 0329             0534 0544             1043 1043             0390 0392
Descripcio_dia_setmana                    Dilluns               Dijous                Dissabte              Diumenge              Dimecres
Dia_setmana                               20200320              20200831              20201103              20201009              20200923
Descripcio_tipus_dia                      Laboral
Any                                       2016.0                2017.0                2018.0
Mes_any                                   4.0                   10.0                  11.0                  8.0                   7.0
Nom_mes                                   Desembre              Octubre               Abril                 Maig                  Gener
Dia_mes                                   11                    19                    24                    30                    14
Descripcio_torn                           Nit                   Matí                  Tarda
Hora_dia                                  3                     12                    5                     13                    1
Descripcio_causa_vianant                  Altres                Transitar a peu per   Desobeir el senyal d  Creuar per fora pas   Desobeir altres seny
Desc_Tipus_vehicle_implicat               Otros vehíc. a motor  Ambulància            Tricicle              Tranvía o tren        Cuadriciclo >=75cc
Descripcio_sexe                           Home                  Dona                  Desconegut
Edat                                      62                    88                    92                    70                    71
Descripcio_tipus_persona                  Conductor             Passatger             Vianant
Descripcio_situacio                       Altres                Desconegut            Presentat             Citado                Otros
Descripcio_victimitzacio                  Ferit greu            Mort (després de 24h  Ferit lleu: Rebutja   Desconegut            Mort natural
Coordenada_UTM_X                          433340,44             429146.81             432203,75             432214.51             426771.96
Coordenada_UTM_Y                          4581525,98            4582594.5             4581833.72            4587518,43            4576056.67
Longitud                                  2.16123               2.14872701            2.208519              2,185704              2.206687
Latitud                                   41.38561              41.44196              41.423528             41.45368864207788     41.44299867067932
Mes_ any                                  2.0                   11.0                  7.0                   1.0                   3.0
Numero_Expedient                          2020S000327           2021S002507           2020S002807           2021S004527           2019S001115
Num_postal                                0310 0310             660000                0017 0037             1560000               0325 0327
NK_ Any                                   2019.0                2020.0                2021.0                2022.0
Descripcio_Lloc_atropellament_vianat      A la vorera / Andana  Fora del pas          Desconegut            N/A                   En pas regulat per s
Descripcio_Motiu_desplaçament_vianant     Servei de neteja, re  Bombers, policia, am  In itinere            Altres activitats     Desconegut
Descripcio_Motiu_desplaçament_conductor   Bus de línia discrec  Anada/tornada de pon  Activitat esportiva   En missió             En pràctiques d'auto
Descripció_sexe                           Dona                  Home                  Desconegut
Descripció_tipus_persona                  Conductor             Vianant               Passatger             Desconegut
Descripcio_Motiu_desplaĂ§ament_vianant    Altres activitats     In itinere            Oci i entreteniment   Bombers, policia, am  Desconegut
Descripcio_Motiu_desplaĂ§ament_conductor  Servei de neteja o r  Bus de línia discrec  Es desconeix          In itínere            Servei de mantenimen
Descripcio_Motiu_desplaÃ§ament_vianant    Bombers, policia, am  En missió             Altres activitats     Desconegut            In itinere
Descripcio_Motiu_desplaÃ§ament_conductor  Bombers, policia, am  Activitat esportiva   En pràctiques d'auto  Taxi                  Bus de línia regular
Coordenada_UTM_X_ED50                     430138.0              430641.58             428687.16             430259.12             427534.02
Coordenada_UTM_Y_ED50                     4587570.09            4588795.75            4586555.73            4582222.93            4578975.16
Longitud_WGS84                            2.133192842           2.167888871           2.107643777           2.145274895           2.190946319
Latitud_WGS84                             41.445818079          41.391045298          41.414124185          41.405694255          41.39733781
Descripcio_Lloc_atropellament_vianant     En pas regulat per s  Altres                A la vorera / Andana  En pas sense senyali  En pas sense regular

En este caso, de las 46 columnas, detectamos que hay muchas que siguen dando información duplicada. Con el mismo objetivo que en los casos anteriores, deseamos unir las columnas que tratan la misma información. En concreto, igualaremos la siguientes columnas:

- 'Numero_expedient' = 'Numero_Expedient'. Ambos refieren al número identificativo de cada uno de los expedientes

- 'Num_postal' ='Num_postal '

- 'Any' = 'NK_ Any'

- 'Mes_any' = 'Mes_ any'

- 'Descripcio_sexe' = 'Descripció_sexe'

- 'Descripcio_tipus_persona' = 'Descripció_tipus_persona'

- 'Coordenada_UTM_X'= 'Coordenada_UTM_X_ED50'

- 'Coordenada_UTM_Y' = 'Coordenada_UTM_Y_ED50'

- 'Longitud' = 'Longitud_WGS84'

- 'Latitud' = 'Latitud_WGS84'

- 'Descripcio_Lloc_atropellament_vianant' = 'Descripcio_Lloc_atropellament_vianat'

- 'Descripcio_Motiu_desplaçament_vianant' = 'Descripcio_Motiu_desplaĂ§ament_vianant' , 'Descripcio_Motiu_desplaÃ§ament_vianant'

- 'Descripcio_Motiu_desplaçament_conductor' = 'Descripcio_Motiu_desplaĂ§ament_conductor' , 'Descripcio_Motiu_desplaÃ§ament_conductor'

In [ ]:
#Fusionamos Numero_expedient con Numero_Expedient y eliminamos Numero_Expedient
df_6['Numero_expedient'] = df_6['Numero_expedient'].combine_first(df_6["Numero_Expedient"])
df_6.drop(columns="Numero_Expedient", inplace=True)

#Fusionamos Num_postal con Num_postal  y eliminamos Num_postal
df_6['Num_postal'] = df_6['Num_postal'].combine_first(df_6["Num_postal "])
df_6.drop(columns="Num_postal ", inplace=True)

#Fusionamos Any con NK_ Any  y eliminamos NK_ Any
df_6['Any'] = df_6['Any'].combine_first(df_6["NK_ Any"])
df_6.drop(columns="NK_ Any", inplace=True)

#Fusionamos Mes_any con Mes_ any  y eliminamos Mes_ any
df_6['Mes_any'] = df_6['Mes_any'].combine_first(df_6["Mes_ any"])
df_6.drop(columns="Mes_ any", inplace=True)

#Fusionamos Descripcio_sexe con Descripció_sexe y eliminamos Descripció_sexe
df_6['Descripcio_sexe'] = df_6['Descripcio_sexe'].combine_first(df_6["Descripció_sexe"])
df_6.drop(columns="Descripció_sexe", inplace=True)

#Fusionamos Descripcio_tipus_persona con Descripció_tipus_persona y eliminamos Descripció_tipus_persona
df_6['Descripcio_tipus_persona'] = df_6['Descripcio_tipus_persona'].combine_first(df_6["Descripció_tipus_persona"])
df_6.drop(columns="Descripció_tipus_persona", inplace=True)

#Fusionamos Coordenada_UTM_X con Coordenada_UTM_X_ED50 y eliminamos Coordenada_UTM_X_ED50
df_6['Coordenada_UTM_X'] = df_6['Coordenada_UTM_X'].combine_first(df_6["Coordenada_UTM_X_ED50"])
df_6.drop(columns="Coordenada_UTM_X_ED50", inplace=True)

#Fusionamos Coordenada_UTM_Y con Coordenada_UTM_Y_ED50 y eliminamos Coordenada_UTM_Y_ED50
df_6['Coordenada_UTM_Y'] = df_6['Coordenada_UTM_Y'].combine_first(df_6["Coordenada_UTM_Y_ED50"])
df_6.drop(columns="Coordenada_UTM_Y_ED50", inplace=True)

#Fusionamos Longitud con Longitud_WGS84 y eliminamos Longitud_WGS84
df_6['Longitud'] = df_6['Longitud'].combine_first(df_6["Longitud_WGS84"])
df_6.drop(columns="Longitud_WGS84", inplace=True)

#Fusionamos Latitud con Latitud_WGS84 y eliminamos Latitud_WGS84
df_6['Latitud'] = df_6['Latitud'].combine_first(df_6["Latitud_WGS84"])
df_6.drop(columns="Latitud_WGS84", inplace=True)

#Fusionamos Descripcio_Lloc_atropellament_vianant con Descripcio_Lloc_atropellament_vianat y eliminamos Descripcio_Lloc_atropellament_vianat
df_6['Descripcio_Lloc_atropellament_vianant'] = df_6['Descripcio_Lloc_atropellament_vianant'].combine_first(df_6["Descripcio_Lloc_atropellament_vianat"])
df_6.drop(columns="Descripcio_Lloc_atropellament_vianat", inplace=True)

#Fusionamos Descripcio_Motiu_desplaçament_vianant con Descripcio_Motiu_desplaĂ§ament_vianant y Descripcio_Motiu_desplaÃ§ament_vianant y eliminamos Descripcio_Motiu_desplaĂ§ament_vianant y Descripcio_Motiu_desplaÃ§ament_vianant
df_6['Descripcio_Motiu_desplaçament_vianant']=df_6['Descripcio_Motiu_desplaçament_vianant'].combine_first(df_6['Descripcio_Motiu_desplaĂ§ament_vianant']).combine_first(df_6['Descripcio_Motiu_desplaÃ§ament_vianant'])
df_6.drop(columns=['Descripcio_Motiu_desplaĂ§ament_vianant','Descripcio_Motiu_desplaÃ§ament_vianant'],inplace=True)

#Fusionamos Descripcio_Motiu_desplaçament_conductor con Descripcio_Motiu_desplaĂ§ament_conductor y Descripcio_Motiu_desplaÃ§ament_vianant y eliminamos Descripcio_Motiu_desplaĂ§ament_conductor y Descripcio_Motiu_desplaÃ§ament_conductor
df_6['Descripcio_Motiu_desplaçament_conductor']=df_6['Descripcio_Motiu_desplaçament_conductor'].combine_first(df_6['Descripcio_Motiu_desplaĂ§ament_conductor']).combine_first(df_6['Descripcio_Motiu_desplaÃ§ament_conductor'])
df_6.drop(columns=['Descripcio_Motiu_desplaĂ§ament_conductor','Descripcio_Motiu_desplaÃ§ament_conductor'],inplace=True)

# Convertir columnas a tipos adecuados
df_6['Any'] = df_6['Any'].astype(int)  # Convertir 'Any' a tipo entero
df_6['Mes_any'] = df_6['Mes_any'].astype(int)

# Convertir al tipo correcto
df_6.loc[df_6['Edat'] == "Desconegut", 'Edat'] = -1
df_6['Edat'] = df_6['Edat'].astype(int)

df_6['Latitud'] = df_6['Latitud'].astype(str)
df_6['Longitud'] = df_6['Longitud'].astype(str)

df_6['Latitud'] = df_6['Latitud'].str.replace(',', '.')
df_6['Longitud'] = df_6['Longitud'].str.replace(',', '.')

# Reemplazar los valores de la columna 'Latitud' que son simplemente un string vacío por -1
df_6.loc[df_6['Latitud'] == "'", 'Latitud'] = -1
df_6.loc[df_6['Longitud'] == "'", 'Longitud'] = -1

df_6['Longitud'] = df_6['Longitud'].astype(float)
df_6['Latitud'] = df_6['Latitud'].astype(float)

Antes de seguir eliminando columnas duplicadas, intentaremos ver si podemos rellenar los NaNs con las existentes.

En principio, nos gustaría mantener las columnas de Longitud y Latitud, y eliminar las Coordenadas_UTM_X y las Coordenadas_UTM_Y. Sin embargo, debido a la presencia de NaNs en las columnas de Longitud y Latitud, miraremos primero si podemos quitar esos NaNs reemplazándolos con los valores de las coordenadas UTM

Como, en ambos casos, no podemos reemplazar ningún valor nulo, decidimos eliminar las columnas de Coordenada_UTM_X y de Coordenada_UTM_Y. Además, eliminamos las siguientes columnas que no son necesarias ya que, aquellas que incluyen la misma información, no tienen nulos.

In [ ]:
#decidimos eliminar las columnas
df_6.drop(columns=['Coordenada_UTM_X','Coordenada_UTM_Y', 'Dia_setmana','Descripcio_tipus_dia','Nom_mes'],inplace=True)

In [ ]:
df_6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79647 entries, 0 to 79646
Data columns (total 26 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Numero_expedient                         79647 non-null  object
 1   Codi_districte                           79647 non-null  int64
 2   Nom_districte                            79647 non-null  object
 3   Codi_barri                               79647 non-null  int64
 4   Nom_barri                                79647 non-null  object
 5   Codi_carrer                              79647 non-null  int64
 6   Nom_carrer                               74359 non-null  object
 7   Descripcio_dia_setmana                   79647 non-null  object
 8   Any                                      79647 non-null  int64
 9   Mes_any                                  79647 non-null  int64
 10  Dia_mes                                  79647 non-null  int64
 11  Descripcio_torn                          79647 non-null  object
 12  Hora_dia                                 79647 non-null  int64
 13  Descripcio_causa_vianant                 79647 non-null  object
 14  Desc_Tipus_vehicle_implicat              79647 non-null  object
 15  Descripcio_sexe                          79647 non-null  object
 16  Edat                                     79647 non-null  int64
 17  Descripcio_tipus_persona                 79647 non-null  object
 18  Descripcio_situacio                      36074 non-null  object
 19  Descripcio_victimitzacio                 79647 non-null  object
 20  Longitud                                 79525 non-null  float64
 21  Latitud                                  79525 non-null  float64
 22  Num_postal                               72371 non-null  object
 23  Descripcio_Motiu_desplaçament_vianant    43573 non-null  object
 24  Descripcio_Motiu_desplaçament_conductor  43573 non-null  object
 25  Descripcio_Lloc_atropellament_vianant    43573 non-null  object
dtypes: float64(2), int64(8), object(16)
memory usage: 15.8+ MB

In [ ]:
df_6.isna().sum()

Numero_expedient                               0
Codi_districte                                 0
Nom_districte                                  0
Codi_barri                                     0
Nom_barri                                      0
Codi_carrer                                    0
Nom_carrer                                  5288
Descripcio_dia_setmana                         0
Any                                            0
Mes_any                                        0
Dia_mes                                        0
Descripcio_torn                                0
Hora_dia                                       0
Descripcio_causa_vianant                       0
Desc_Tipus_vehicle_implicat                    0
Descripcio_sexe                                0
Edat                                           0
Descripcio_tipus_persona                       0
Descripcio_situacio                        43573
Descripcio_victimitzacio                       0
Longitud                                     122
Latitud                                      122
Num_postal                                  7276
Descripcio_Motiu_desplaçament_vianant      36074
Descripcio_Motiu_desplaçament_conductor    36074
Descripcio_Lloc_atropellament_vianant      36074
dtype: int64

In [ ]:
df_6[df_6['Codi_carrer']==32700]['Nom_carrer'].value_counts()

Nom_carrer
Balmes                                                675
Balmes                                                 85
Diagonal / Gràcia                                      12
Balmes / Còrsega                                        9
Aragó                                                   7
Aribau                                                  6
Balmes / València                                       6
Balmes / Provença                                       6
Balmes / Aragó                                          5
Balmes / Rosselló                                       5
Diagonal / Aribau                                       5
Balmes / Corts Catalanes                                5
Aragó / Catalunya                                       5
Balmes / Gràcia                                         4
Mallorca / Aribau                                       4
Balmes / Mallorca                                       4
Aragó / Balmes                                          4
Balmes / Marià Cubí                                     3
Balmes / Diagonal                                       3
Balmes / Santjoanistes                                  3
Gràcia / Augusta                                        3
Balmes / Sant Eusebi                                    3
Balmes / Diputació                                      3
Sant Gervasi / Lleó XIII                                2
Diagonal / Balmes                                       2
Aribau / València                                       2
Cinc d'Oros                                             2
Aribau / Marià Cubí                                     2
Sant Gervasi                                            2
Portolà                                                 2
Augusta                                                 2
Aribau / Mallorca                                       2
Balmes / Pàdua                                          2
Gràcia / Diagonal                                       2
Balmes / Sant Elies                                     1
Provença / Balmes                                       1
Balmes / Laforja                                        1
General Mitre / Balmes                                  1
Balmes / Consell de Cent                                1
Corts Catalanes                                         1
Corts Catalanes / Balmes                                1
Sant Elies / Balmes                                     1
General Mitre / Atenes                                  1
Balmes / Narcisa Freixas                                1
Balmes / Putxet                                         1
Provença / Muntaner                                     1
Balmes / Madrazo                                        1
Moragas / Folgueroles                                   1
Balmes / Córcega                                        1
Balmes / Comte de Salvatierra                           1
Balmes / Copèrnic                                       1
Aragó / Gràcia                                          1
Rosselló / Pau Claris                                   1
General Mitre / Sant Gervasi de Cassoles                1
Balmes / Universitat                                    1
Name: count, dtype: int64

### Convertir los *dataframes* a .csv

In [ ]:
dataframes = [df_1, df_2, df_3, df_4, df_5, df_6]

for df in dataframes:
    if 'Numero_expedient' in df.columns:
        df['Numero_expedient'] = df['Numero_expedient'].str.strip()

<ipython-input-42-c2498fd133ab>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Numero_expedient'] = df['Numero_expedient'].str.strip()

In [ ]:
for df in dataframes:
  df.sort_values(by='Numero_expedient', inplace=True)
  df.drop_duplicates(inplace=True)

print('Número de observaciones del dataframe 1:', df_1.shape)
print('Número de observaciones del dataframe 2:', df_2.shape)
print('Número de observaciones del dataframe 3:', df_3.shape)
print('Número de observaciones del dataframe 4:', df_4.shape)
print('Número de observaciones del dataframe 5:', df_5.shape)
print('Número de observaciones del dataframe 6:', df_6.shape)

Número de observaciones del dataframe 1: (69355, 18)
Número de observaciones del dataframe 2: (65271, 16)
Número de observaciones del dataframe 3: (62368, 22)
Número de observaciones del dataframe 4: (118251, 23)
Número de observaciones del dataframe 5: (62357, 17)
Número de observaciones del dataframe 6: (79647, 26)

In [ ]:
for i, df in enumerate(dataframes, start=1):
    if df['Numero_expedient'].isna().any():
        print(f"Se encontraron NaN en la columna 'Numero_expedient' en el DataFrame df{i}.")
    else:
        print(f"No se encontraron NaN en la columna 'Numero_expedient' en el DataFrame df{i}.")

No se encontraron NaN en la columna 'Numero_expedient' en el DataFrame df1.
No se encontraron NaN en la columna 'Numero_expedient' en el DataFrame df2.
No se encontraron NaN en la columna 'Numero_expedient' en el DataFrame df3.
No se encontraron NaN en la columna 'Numero_expedient' en el DataFrame df4.
No se encontraron NaN en la columna 'Numero_expedient' en el DataFrame df5.
No se encontraron NaN en la columna 'Numero_expedient' en el DataFrame df6.

In [ ]:
df_1['Any'].value_counts()

Any
2017    11091
2019    11025
2018    10835
2016    10510
2022     9320
2021     8979
2020     7595
Name: count, dtype: int64

In [ ]:
df_2['Any'].value_counts()

Any
2017    11009
2016    10701
2018    10551
2019    10536
2022     8098
2021     7796
2020     6580
Name: count, dtype: int64

In [ ]:
df_3['Any'].value_counts()

Any
2017    10339
2016    10140
2019    10027
2018     9936
2022     7999
2021     7659
2020     6268
Name: count, dtype: int64

In [ ]:
df_4['Any'].value_counts()

Any
2017    19795
2016    19409
2018    19079
2019    19025
2022    14901
2021    14343
2020    11699
Name: count, dtype: int64

In [ ]:
df_5['Any'].value_counts()

Any
2017    10343
2016    10157
2019    10028
2018     9926
2022     7989
2021     7653
2020     6261
Name: count, dtype: int64

In [ ]:
df_6['Any'].value_counts()

Any
2020    13810
2017    12148
2016    12072
2018    11854
2019    11844
2022     9065
2021     8854
Name: count, dtype: int64

In [ ]:
# Directorio donde se almacenarán los archivos CSV limpios
output_dir = '/content/drive/MyDrive/TFM/clean_data'

# Crear el directorio si no existe
os.makedirs(output_dir, exist_ok=True)

# Guardar el DataFrame general como un archivo CSV
#df_1.to_csv(os.path.join(output_dir, "DatosCausaConductor.csv"), index=False)
#df_2.to_csv(os.path.join(output_dir, "DatosTipoAccidente.csv"), index=False)
#df_3.to_csv(os.path.join(output_dir, "DatosPersonasHeridas.csv"), index=False)
#df_4.to_csv(os.path.join(output_dir, "DatosTipoVehiculo.csv"), index=False)
#df_5.to_csv(os.path.join(output_dir, "DatosCausaMediata.csv"), index=False)
#df_6.to_csv(os.path.join(output_dir, "DatosPersona.csv"), index=False)

Ahora podemos encontrar los *dataframes* limpios en la ruta '/content/drive/MyDrive/TFM/clean_data'

## Juntar los seis *dataframes*

### Ordenar las columnas de los dfs

In [ ]:
# vemos las columnas de cada df
df1_columns = pd.DataFrame({'Columnas_df1': df_1.columns})
df2_columns = pd.DataFrame({'Columnas_df2': df_2.columns})
df3_columns = pd.DataFrame({'Columnas_df3': df_3.columns})
df4_columns = pd.DataFrame({'Columnas_df4': df_4.columns})
df5_columns = pd.DataFrame({'Columnas_df5': df_5.columns})
df6_columns = pd.DataFrame({'Columnas_df6': df_6.columns})

# Concatenamos horizontalmnente
df_columnas = pd.concat([df1_columns, df2_columns, df3_columns, df4_columns, df5_columns, df6_columns], axis=1)

df_columnas

,Columnas_df1,Columnas_df2,Columnas_df3,Columnas_df4,Columnas_df5,Columnas_df6
0,Numero_expedient,Numero_expedient,Numero_expedient,Numero_expedient,Numero_expedient,Numero_expedient
1,Codi_districte,Codi_districte,Codi_districte,Codi_districte,Codi_districte,Codi_districte
2,Nom_districte,Nom_districte,Nom_districte,Nom_districte,Nom_districte,Nom_districte
3,Codi_barri,Codi_barri,Codi_barri,Codi_barri,Codi_barri,Codi_barri
4,Nom_barri,Nom_barri,Nom_barri,Nom_barri,Nom_barri,Nom_barri
5,Codi_carrer,Codi_carrer,Codi_carrer,Codi_carrer,Codi_carrer,Codi_carrer
6,Nom_carrer,Nom_carrer,Nom_carrer,Nom_carrer,Nom_carrer,Nom_carrer
7,Num_postal,Descripcio_dia_setmana,Num_postal,Num_postal,Num_postal,Descripcio_dia_setmana
8,Descripcio_dia_setmana,Any,Descripcio_dia_setmana,Descripcio_dia_setmana,Descripcio_dia_setmana,Any
9,Any,Mes_any,Any,Any,Any,Mes_any
10,Mes_any,Dia_mes,Mes_any,Mes_any,Mes_any,Dia_mes
11,Dia_mes,Hora_dia,Dia_mes,Dia_mes,Dia_mes,Descripcio_torn
12,Hora_dia,Descripcio_torn,Hora_dia,Hora_dia,Hora_dia,Hora_dia
13,Descripcio_torn,Descripcio_tipus_accident,Descripcio_torn,Descripcio_causa_vianant,Descripcio_torn,Descripcio_causa_vianant
14,Descripcio_causa_conductor,Longitud,Descripcio_causa_vianant,Descripcio_tipus_vehicle,Descripcio_causa_mediata,Desc_Tipus_vehicle_implicat
15,Longitud,Latitud,Numero_morts,Descripcio_model,Longitud,Descripcio_sexe
16,Latitud,NaN,Numero_lesionats_lleus,Descripcio_marca,Latitud,Edat
17,Descripcio_causa_mediata,NaN,Numero_lesionats_greus,Descripcio_color,NaN,Descripcio_tipus_persona
18,NaN,NaN,Numero_victimes,Descripcio_carnet,NaN,Descripcio_situacio
19,NaN,NaN,Numero_vehicles_implicats,Antiguitat_carnet,NaN,Descripcio_victimitzacio
20,NaN,NaN,Longitud,Longitud,NaN,Longitud
21,NaN,NaN,Latitud,Latitud,NaN,Latitud
22,NaN,NaN,NaN,Descripcio_torn,NaN,Num_postal
23,NaN,NaN,NaN,NaN,NaN,Descripcio_Motiu_desplaçament_vianant
24,NaN,NaN,NaN,NaN,NaN,Descripcio_Motiu_desplaçament_conductor
25,NaN,NaN,NaN,NaN,NaN,Descripcio_Lloc_atropellament_vianant

In [ ]:
#NUM_POSTAL
# Extraer la columna en el índice 17 y guardarla en una variable temporal
columna = df_2.pop(df_2.columns[16])
# Insertar la columna en el índice 7
df_2.insert(7, columna.name, columna)

# Extraer la columna en el índice 17 y guardarla en una variable temporal
columna = df_6.pop(df_6.columns[22])
# Insertar la columna en el índice 7
df_6.insert(7, columna.name, columna)

#DESCRIPCIO TORN
columna = df_6.pop(df_6.columns[12])
df_6.insert(13, columna.name,columna)

columna = df_4.pop(df_4.columns[22])
df_4.insert(13, columna.name,columna)

#LONGITUD Y LATITUD
columna = df_1.pop(df_1.columns[17])
df_1.insert(15, columna.name,columna)

columna = df_6.pop(df_6.columns[21])
df_6.insert(24, columna.name,columna)

columna = df_6.pop(df_6.columns[21])
df_6.insert(25,columna.name,columna)

columna = df_6.pop(df_6.columns[23])
df_6.insert(24,columna.name,columna)

IndexError: index 16 is out of bounds for axis 0 with size 16

In [ ]:
# vemos las columnas de cada df
df1_columns = pd.DataFrame({'Columnas_df1': df_1.columns})
df2_columns = pd.DataFrame({'Columnas_df2': df_2.columns})
df3_columns = pd.DataFrame({'Columnas_df3': df_3.columns})
df4_columns = pd.DataFrame({'Columnas_df4': df_4.columns})
df5_columns = pd.DataFrame({'Columnas_df5': df_5.columns})
df6_columns = pd.DataFrame({'Columnas_df6': df_6.columns})

# Concatenamos horizontalmnente
df_columnas = pd.concat([df1_columns, df2_columns, df3_columns, df4_columns, df5_columns, df6_columns], axis=1)

df_columnas

Ahora ya tenemos todas las columnas bien ordenadas en nuestro conjunto de datasets.

A continuacón, nos interesa gestionar los valores duplicados en el número de expediente, que será la clave por la cual vamos a juntar los datasets.

### Valores duplicados en número de expediente

Hay que tener en cuenta los duplicados de Numero de expediente en cada uno de los datasets. En este apartado, queremos ver si realmente existen estos valores duplicados.

Tomaremos como ejemplo los valores de numero de expediente repetidos en un df de ejemplo, el 4 en este caso.

In [ ]:
df_4['Numero_expedient'].nunique()

62262

In [ ]:
df_4.shape

(118251, 23)

A simple vista, vemos como hay algo que no cuadra. Nuestro dataframe tiene una longitud de 118251, y tenemos 62262 valores distintos de numero de expediente. Como ya se han eliminado los NaNs anteriormente, sabemos que existirán valores reptidos. A continuación, procedemos a explorar algunos ejemplos de valores repetidos

In [ ]:
#usamos la función 'duplicated'
duplicados_df4 = df_4[df_4.duplicated(subset='Numero_expedient', keep=False)]
duplicados_df4

,Numero_expedient,Codi_districte,Nom_districte,Codi_barri,Nom_barri,Codi_carrer,Nom_carrer,Num_postal,Descripcio_dia_setmana,Any,Mes_any,Dia_mes,Hora_dia,Descripcio_causa_vianant,Descripcio_tipus_vehicle,Descripcio_model,Descripcio_marca,Descripcio_color,Descripcio_carnet,Antiguitat_carnet,Longitud,Latitud,Descripcio_torn
6575,2016S000001,2,Eixample,7,la Dreta de l'Eixample,144601,Diagonal,0361B0361B,Divendres,2016,1,1,0,No és causa del vianant,Turismo,S40,VOLVO,Blau,B,53,2.163202,41.397223,NaN
6574,2016S000001,2,Eixample,7,la Dreta de l'Eixample,144601,Diagonal,0361B0361B,Divendres,2016,1,1,0,No és causa del vianant,Taxi,Altea,SEAT,Altres,BTP,10,2.163202,41.397223,NaN
15781,2016S000003,8,Nou Barris,53,la Trinitat Nova,209900,Meridiana,0595X0595X,Divendres,2016,1,1,5,No és causa del vianant,Motocicleta,SH 125,HONDA,Negre,B,4,2.187925,41.448446,NaN
15782,2016S000003,8,Nou Barris,53,la Trinitat Nova,209900,Meridiana,0595X0595X,Divendres,2016,1,1,5,No és causa del vianant,Turismo,307,PEUGEOT,Negre,B,11,2.187925,41.448446,NaN
5318,2016S000004,2,Eixample,8,l'Antiga Esquerra de l'Eixample,32700,Balmes,0119 0119,Divendres,2016,1,1,6,No és causa del vianant,Taxi,Altea,SEAT,Negre/Groc,B,8,2.158167,41.392530,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113213,2022S008012,6,Gràcia,31,la Vila de Gràcia,90502,Còrsega ...,0339 0339,Dimarts,2022,12,6,10,No és causa del vianant,Turisme,FIAT PANDA,FIAT,Blanc,B,7,2.160867,41.397829,Matí
107068,2022S008013,2,Eixample,8,l'Antiga Esquerra de l'Eixample,32700,Balmes ...,0083 0083,Dissabte,2022,12,10,1,No és causa del vianant,Motocicleta,SEAT MÓ ESCOOTER 125,SILENCE,Desconegut,B,9,2.160225,41.390994,Nit
107069,2022S008013,2,Eixample,8,l'Antiga Esquerra de l'Eixample,32700,Balmes ...,0083 0083,Dissabte,2022,12,10,1,No és causa del vianant,Taxi,Desconegut,Desconegut,Desconegut,Desconegut,-1,2.160225,41.390994,Nit
112980,2023S000004,6,Gràcia,28,Vallcarca i els Penitents,279600,República Argentina ...,0068 0068,Dissabte,2022,12,31,15,No és causa del vianant,Bicicleta,Desconegut,Desconegut,Negre,B,23,2.146288,41.409862,Tarda
112981,2023S000004,6,Gràcia,28,Vallcarca i els Penitents,279600,República Argentina ...,0068 0068,Dissabte,2022,12,31,15,No és causa del vianant,Motocicleta,SH 125,HONDA,Desconegut,B,23,2.146288,41.409862,Tarda

#### Gestión y corrección de valores duplicados

Como hemos observado, tenemos valores duplicados en la columna 'Numero_expedient'. Como nos interesa mantener la información de las distintas observaciones - ya que cada una de las filas duplicadas da información diferente, por ejemplo información de los diferentes vehículos implicados en el accidete (uno por cada fila)- el objetivo será añadir columnas para almacenar la información de cada accidente en una sola fila, en lugar de en varias. Todo esto con el objetivo de poder juntar los seis dataframes en uno solo.

Observamos que hay muchos valores que tienen espacios después de los carácteres alfanuméricos. Eliminamos estos espacios, mediante la función "strip()"

In [ ]:
dataframes = [df_1, df_2, df_3, df_4, df_5, df_6]

for df in dataframes:
    if 'Numero_expedient' in df.columns:
        df['Numero_expedient'] = df['Numero_expedient'].str.strip()

In [ ]:
for df in dataframes:
  df.sort_values(by='Numero_expedient', inplace=True)
  df.drop_duplicates(inplace=True)

print('Número de observaciones del dataframe 1:', df_1.shape)
print('Número de observaciones del dataframe 2:', df_2.shape)
print('Número de observaciones del dataframe 3:', df_3.shape)
print('Número de observaciones del dataframe 4:', df_4.shape)
print('Número de observaciones del dataframe 5:', df_5.shape)
print('Número de observaciones del dataframe 6:', df_6.shape)

Número de observaciones del dataframe 1: (69355, 18)
Número de observaciones del dataframe 2: (65271, 16)
Número de observaciones del dataframe 3: (62368, 22)
Número de observaciones del dataframe 4: (118251, 23)
Número de observaciones del dataframe 5: (62357, 17)
Número de observaciones del dataframe 6: (79647, 26)

También comprobaremos que no haya ningún "NaN" que nos dificulte la conversión.

In [ ]:
for i, df in enumerate(dataframes, start=1):
    if df['Numero_expedient'].isna().any():
        print(f"Se encontraron NaN en la columna 'Numero_expedient' en el DataFrame df{i}.")
    else:
        print(f"No se encontraron NaN en la columna 'Numero_expedient' en el DataFrame df{i}.")

No se encontraron NaN en la columna 'Numero_expedient' en el DataFrame df1.
No se encontraron NaN en la columna 'Numero_expedient' en el DataFrame df2.
No se encontraron NaN en la columna 'Numero_expedient' en el DataFrame df3.
No se encontraron NaN en la columna 'Numero_expedient' en el DataFrame df4.
No se encontraron NaN en la columna 'Numero_expedient' en el DataFrame df5.
No se encontraron NaN en la columna 'Numero_expedient' en el DataFrame df6.

##### Dataframe tipo 1

In [ ]:
df_1['Numero_expedient'].value_counts()

Numero_expedient
2018S005514    5
2020S005949    4
2021S001038    4
2022S007550    4
2020S005239    4
              ..
2018S000847    1
2018S000848    1
2018S000849    1
2018S000850    1
2023S000550    1
Name: count, Length: 62232, dtype: int64

In [ ]:
# Combinar las filas idénticas en una sola fila
df1 = df_1.groupby(['Numero_expedient', 'Codi_carrer']).agg({'Descripcio_torn': ', '.join}).reset_index()

In [ ]:
df1['Numero_expedient'].value_counts()

Numero_expedient
2016S000001    1
2020S001186    1
2020S001158    1
2020S001159    1
2020S001160    1
              ..
2018S000356    1
2018S000357    1
2018S000358    1
2018S000359    1
2023S000550    1
Name: count, Length: 62232, dtype: int64

##### Dataframe tipo 2

In [ ]:
df_2['Numero_expedient'].value_counts()

Numero_expedient
2016S008302    4
2019S004374    4
2020S003968    4
2018S003112    4
2019S004185    4
              ..
2018S000913    1
2018S000915    1
2018S000916    1
2018S000917    1
2023S000550    1
Name: count, Length: 62332, dtype: int64

In [ ]:
# Combinar las filas idénticas en una sola fila
df2 = df_2.groupby(['Numero_expedient', 'Codi_carrer']).agg({'Descripcio_tipus_accident': ', '.join}).reset_index()

df2.rename(columns={'Codi_carrer': 'Codi_carrer2'}, inplace=True)

In [ ]:
df2['Numero_expedient'].value_counts()

Numero_expedient
2016S000001    1
2020S001154    1
2020S001126    1
2020S001127    1
2020S001128    1
              ..
2018S000308    1
2018S000309    1
2018S000310    1
2018S000311    1
2023S000550    1
Name: count, Length: 62332, dtype: int64

##### Dataframe tipo 3

In [ ]:
df_3['Numero_expedient'].value_counts()

Numero_expedient
2018S000183    2
2020S000778    2
2020S004479    2
2018S003156    2
2022S002608    2
              ..
2018S000310    1
2018S000311    1
2018S000312    1
2018S000313    1
2023S000550    1
Name: count, Length: 62331, dtype: int64

In [ ]:
# Combinar las filas idénticas en una sola fila
df3 = df_3.groupby(['Numero_expedient', 'Codi_carrer', 'Numero_morts', 'Numero_lesionats_lleus', 'Numero_lesionats_greus',
     'Numero_victimes', 'Numero_vehicles_implicats']).agg({'Descripcio_causa_vianant': ', '.join}).reset_index()

df3.rename(columns={'Codi_carrer': 'Codi_carrer3'}, inplace=True)

In [ ]:
df3['Numero_expedient'].value_counts()

Numero_expedient
2016S000001    1
2020S001154    1
2020S001126    1
2020S001127    1
2020S001128    1
              ..
2018S000308    1
2018S000309    1
2018S000310    1
2018S000311    1
2023S000550    1
Name: count, Length: 62331, dtype: int64

##### Dataframe tipo 4

In [ ]:
df_4['Numero_expedient'].value_counts()

Numero_expedient
2019S008334    18
2019S001628    17
2019S003298    16
2021S002120    14
2017S000147    13
               ..
2021S002709     1
2021S002711     1
2021S002712     1
2017S000649     1
2023S000550     1
Name: count, Length: 62262, dtype: int64

In [ ]:
# Convertir las columnas con valores mixtos en cadenas
df_4[['Descripcio_causa_vianant', 'Descripcio_tipus_vehicle', 'Descripcio_model',
       'Descripcio_marca', 'Descripcio_color', 'Descripcio_carnet', 'Codi_carrer', 'Numero_expedient', 'Antiguitat_carnet']] = df_4[['Descripcio_causa_vianant', 'Descripcio_tipus_vehicle', 'Descripcio_model',
                                                                            'Descripcio_marca', 'Descripcio_color', 'Descripcio_carnet', 'Codi_carrer', 'Numero_expedient', 'Antiguitat_carnet']].astype(str)

# Combinar las filas idénticas en una sola fila
df4 = df_4.groupby(['Numero_expedient', 'Codi_carrer']).agg({
    'Descripcio_causa_vianant': ', '.join,
    'Descripcio_tipus_vehicle': ', '.join,
    'Descripcio_model': ', '.join,
    'Descripcio_marca': ', '.join,
    'Descripcio_color': ', '.join,
    'Descripcio_carnet': ', '.join,
    'Antiguitat_carnet': ', '.join
}).reset_index()

df4.rename(columns={'Codi_carrer': 'Codi_carrer4'}, inplace=True)

In [ ]:
df4['Numero_expedient'].value_counts()

Numero_expedient
2016S000001    1
2020S001161    1
2020S001133    1
2020S001134    1
2020S001135    1
              ..
2018S000317    1
2018S000318    1
2018S000319    1
2018S000320    1
2023S000550    1
Name: count, Length: 62262, dtype: int64

##### Dataframe tipo 5

In [ ]:
df_5['Numero_expedient'].value_counts()

Numero_expedient
2016S007882    2
2016S003497    2
2016S006066    2
2016S007767    2
2016S006144    2
              ..
2018S000325    1
2018S000326    1
2018S000327    1
2018S000328    1
2023S000550    1
Name: count, Length: 62332, dtype: int64

In [ ]:
# Combinar las filas idénticas en una sola fila
df5 = df_5.groupby(['Numero_expedient', 'Codi_districte', 'Nom_districte', 'Codi_barri', 'Nom_barri', 'Codi_carrer', 'Nom_carrer', #'Num_postal',
    'Descripcio_dia_setmana', 'Any', 'Mes_any', 'Dia_mes', 'Hora_dia', 'Descripcio_torn', 'Longitud', 'Latitud']).agg({'Descripcio_causa_mediata': ', '.join}).reset_index()

df5.rename(columns={'Codi_carrer': 'Codi_carrer5'}, inplace=True)

In [ ]:
df5['Numero_expedient'].value_counts()

Numero_expedient
2016S000001    1
2020S001138    1
2020S001110    1
2020S001111    1
2020S001112    1
              ..
2018S000300    1
2018S000301    1
2018S000302    1
2018S000303    1
2023S000550    1
Name: count, Length: 62308, dtype: int64

##### Dataframe tipo 6

In [ ]:
df_6['Numero_expedient'].value_counts()

Numero_expedient
2016S006967    21
2019S004830    21
2019S006444    12
2018S006493    12
2021S003925    12
               ..
2018S002959     1
2018S002961     1
2018S002962     1
2018S002963     1
2023S000550     1
Name: count, Length: 57686, dtype: int64

In [ ]:
# Convertir las columnas con valores mixtos en cadenas
df_6[['Descripcio_sexe', 'Edat', 'Descripcio_tipus_persona', 'Descripcio_situacio', 'Descripcio_victimitzacio',
      'Descripcio_Motiu_desplaçament_vianant', 'Descripcio_Motiu_desplaçament_conductor',
      'Descripcio_Lloc_atropellament_vianant']] = df_6[['Descripcio_sexe', 'Edat', 'Descripcio_tipus_persona',
                                                       'Descripcio_situacio', 'Descripcio_victimitzacio',
                                                       'Descripcio_Motiu_desplaçament_vianant',
                                                       'Descripcio_Motiu_desplaçament_conductor',
                                                       'Descripcio_Lloc_atropellament_vianant']].astype(str)

# Combinar las filas idénticas en una sola fila
df6 = df_6.groupby(['Numero_expedient', 'Codi_carrer']).agg({
    'Descripcio_sexe': ', '.join,
    'Edat': ', '.join,
    'Descripcio_tipus_persona': ', '.join,
    'Descripcio_situacio': ', '.join,
    'Descripcio_victimitzacio': ', '.join,
    'Descripcio_Motiu_desplaçament_vianant': ', '.join,
    'Descripcio_Motiu_desplaçament_conductor': ', '.join,
    'Descripcio_Lloc_atropellament_vianant': ', '.join
}).reset_index()

df6.rename(columns={'Codi_carrer': 'Codi_carrer6'}, inplace=True)

In [ ]:
df6['Numero_expedient'].value_counts()

Numero_expedient
2016S000001    1
2020S001207    1
2020S001237    1
2020S001238    1
2020S001239    1
              ..
2018S000498    1
2018S000499    1
2018S000500    1
2018S000501    1
2023S000550    1
Name: count, Length: 57686, dtype: int64

##### Merge

In [ ]:
dataframes = [df1, df2, df3, df4, df5, df6]

for df in dataframes:
  df.sort_values(by='Numero_expedient', inplace=True)
  df.drop_duplicates(inplace=True)

print('Número de observaciones del dataframe 1:', df1.shape)
print('Número de observaciones del dataframe 2:', df2.shape)
print('Número de observaciones del dataframe 3:', df3.shape)
print('Número de observaciones del dataframe 4:', df4.shape)
print('Número de observaciones del dataframe 5:', df5.shape)
print('Número de observaciones del dataframe 6:', df6.shape)

Número de observaciones del dataframe 1: (62232, 3)
Número de observaciones del dataframe 2: (62332, 3)
Número de observaciones del dataframe 3: (62331, 8)
Número de observaciones del dataframe 4: (62262, 9)
Número de observaciones del dataframe 5: (62308, 16)
Número de observaciones del dataframe 6: (57686, 10)

In [ ]:
df_general = pd.merge(df5, df3, on = ['Numero_expedient'], how = 'left')

print(df_general.columns)
print(df_general.shape)

df_general2 = pd.merge(df_general, df2, on = ['Numero_expedient'], how = 'left')

print(df_general2.columns)
print(df_general2.shape)

df_general3 = pd.merge(df_general2, df4, on = ['Numero_expedient'], how = 'left')

print(df_general3.columns)
print(df_general3.shape)

df_general4 = pd.merge(df_general3, df6, on = ['Numero_expedient'], how = 'left')

print(df_general4.columns)
print(df_general4.shape)

Index(['Numero_expedient', 'Codi_districte', 'Nom_districte', 'Codi_barri',
       'Nom_barri', 'Codi_carrer5', 'Nom_carrer', 'Descripcio_dia_setmana',
       'Any', 'Mes_any', 'Dia_mes', 'Hora_dia', 'Descripcio_torn', 'Longitud',
       'Latitud', 'Descripcio_causa_mediata', 'Codi_carrer3', 'Numero_morts',
       'Numero_lesionats_lleus', 'Numero_lesionats_greus', 'Numero_victimes',
       'Numero_vehicles_implicats', 'Descripcio_causa_vianant'],
      dtype='object')
(62308, 23)
Index(['Numero_expedient', 'Codi_districte', 'Nom_districte', 'Codi_barri',
       'Nom_barri', 'Codi_carrer5', 'Nom_carrer', 'Descripcio_dia_setmana',
       'Any', 'Mes_any', 'Dia_mes', 'Hora_dia', 'Descripcio_torn', 'Longitud',
       'Latitud', 'Descripcio_causa_mediata', 'Codi_carrer3', 'Numero_morts',
       'Numero_lesionats_lleus', 'Numero_lesionats_greus', 'Numero_victimes',
       'Numero_vehicles_implicats', 'Descripcio_causa_vianant', 'Codi_carrer2',
       'Descripcio_tipus_accident'],
      dtype='object')
(62308, 25)
Index(['Numero_expedient', 'Codi_districte', 'Nom_districte', 'Codi_barri',
       'Nom_barri', 'Codi_carrer5', 'Nom_carrer', 'Descripcio_dia_setmana',
       'Any', 'Mes_any', 'Dia_mes', 'Hora_dia', 'Descripcio_torn', 'Longitud',
       'Latitud', 'Descripcio_causa_mediata', 'Codi_carrer3', 'Numero_morts',
       'Numero_lesionats_lleus', 'Numero_lesionats_greus', 'Numero_victimes',
       'Numero_vehicles_implicats', 'Descripcio_causa_vianant_x',
       'Codi_carrer2', 'Descripcio_tipus_accident', 'Codi_carrer4',
       'Descripcio_causa_vianant_y', 'Descripcio_tipus_vehicle',
       'Descripcio_model', 'Descripcio_marca', 'Descripcio_color',
       'Descripcio_carnet', 'Antiguitat_carnet'],
      dtype='object')
(62308, 33)
Index(['Numero_expedient', 'Codi_districte', 'Nom_districte', 'Codi_barri',
       'Nom_barri', 'Codi_carrer5', 'Nom_carrer', 'Descripcio_dia_setmana',
       'Any', 'Mes_any', 'Dia_mes', 'Hora_dia', 'Descripcio_torn', 'Longitud',
       'Latitud', 'Descripcio_causa_mediata', 'Codi_carrer3', 'Numero_morts',
       'Numero_lesionats_lleus', 'Numero_lesionats_greus', 'Numero_victimes',
       'Numero_vehicles_implicats', 'Descripcio_causa_vianant_x',
       'Codi_carrer2', 'Descripcio_tipus_accident', 'Codi_carrer4',
       'Descripcio_causa_vianant_y', 'Descripcio_tipus_vehicle',
       'Descripcio_model', 'Descripcio_marca', 'Descripcio_color',
       'Descripcio_carnet', 'Antiguitat_carnet', 'Codi_carrer6',
       'Descripcio_sexe', 'Edat', 'Descripcio_tipus_persona',
       'Descripcio_situacio', 'Descripcio_victimitzacio',
       'Descripcio_Motiu_desplaçament_vianant',
       'Descripcio_Motiu_desplaçament_conductor',
       'Descripcio_Lloc_atropellament_vianant'],
      dtype='object')
(62308, 42)

In [ ]:
# Eliminar columnas
df_general4.drop(columns=['Codi_districte', 'Codi_barri',# 'Num_postal',
                          'Descripcio_causa_vianant_y'], inplace=True)

# Renombrar columna
df_general4.rename(columns={'Descripcio_causa_vianant_x': 'Descripcio_causa_vianant'}, inplace=True)

In [ ]:
df_general4.isna().sum()

Numero_expedient                              0
Nom_districte                                 0
Nom_barri                                     0
Codi_carrer5                                  0
Nom_carrer                                    0
Descripcio_dia_setmana                        0
Any                                           0
Mes_any                                       0
Dia_mes                                       0
Hora_dia                                      0
Descripcio_torn                               0
Longitud                                      0
Latitud                                       0
Descripcio_causa_mediata                      0
Codi_carrer3                                  1
Numero_morts                                  1
Numero_lesionats_lleus                        1
Numero_lesionats_greus                        1
Numero_victimes                               1
Numero_vehicles_implicats                     1
Descripcio_causa_vianant                      1
Codi_carrer2                                  0
Descripcio_tipus_accident                     0
Codi_carrer4                                 69
Descripcio_tipus_vehicle                     69
Descripcio_model                             69
Descripcio_marca                             69
Descripcio_color                             69
Descripcio_carnet                            69
Antiguitat_carnet                            69
Codi_carrer6                               4643
Descripcio_sexe                            4643
Edat                                       4643
Descripcio_tipus_persona                   4643
Descripcio_situacio                        4643
Descripcio_victimitzacio                   4643
Descripcio_Motiu_desplaçament_vianant      4643
Descripcio_Motiu_desplaçament_conductor    4643
Descripcio_Lloc_atropellament_vianant      4643
dtype: int64

In [ ]:
# Convertir las columnas a tipo entero
columns_to_convert = ['Any', 'Mes_any', 'Dia_mes', 'Hora_dia', 'Numero_morts', 'Numero_lesionats_lleus',
                      'Numero_lesionats_greus', 'Numero_victimes', 'Numero_vehicles_implicats',
                      'Codi_carrer5', 'Codi_carrer2' # 'Codi_carrer6', 'Codi_carrer4', 'Codi_carrer3',
                      ]

df_general4[columns_to_convert] = df_general4[columns_to_convert].fillna('-1').astype(int)

In [ ]:
df_general4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62308 entries, 0 to 62307
Data columns (total 39 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Numero_expedient                         62308 non-null  object
 1   Nom_districte                            62308 non-null  object
 2   Nom_barri                                62308 non-null  object
 3   Codi_carrer5                             62308 non-null  int64
 4   Nom_carrer                               62308 non-null  object
 5   Descripcio_dia_setmana                   62308 non-null  object
 6   Any                                      62308 non-null  int64
 7   Mes_any                                  62308 non-null  int64
 8   Dia_mes                                  62308 non-null  int64
 9   Hora_dia                                 62308 non-null  int64
 10  Descripcio_torn                          62308 non-null  object
 11  Longitud                                 62308 non-null  float64
 12  Latitud                                  62308 non-null  float64
 13  Descripcio_causa_mediata                 62308 non-null  object
 14  Codi_carrer3                             62307 non-null  float64
 15  Numero_morts                             62308 non-null  int64
 16  Numero_lesionats_lleus                   62308 non-null  int64
 17  Numero_lesionats_greus                   62308 non-null  int64
 18  Numero_victimes                          62308 non-null  int64
 19  Numero_vehicles_implicats                62308 non-null  int64
 20  Descripcio_causa_vianant                 62307 non-null  object
 21  Codi_carrer2                             62308 non-null  int64
 22  Descripcio_tipus_accident                62308 non-null  object
 23  Codi_carrer4                             62239 non-null  object
 24  Descripcio_tipus_vehicle                 62239 non-null  object
 25  Descripcio_model                         62239 non-null  object
 26  Descripcio_marca                         62239 non-null  object
 27  Descripcio_color                         62239 non-null  object
 28  Descripcio_carnet                        62239 non-null  object
 29  Antiguitat_carnet                        62239 non-null  object
 30  Codi_carrer6                             57665 non-null  float64
 31  Descripcio_sexe                          57665 non-null  object
 32  Edat                                     57665 non-null  object
 33  Descripcio_tipus_persona                 57665 non-null  object
 34  Descripcio_situacio                      57665 non-null  object
 35  Descripcio_victimitzacio                 57665 non-null  object
 36  Descripcio_Motiu_desplaçament_vianant    57665 non-null  object
 37  Descripcio_Motiu_desplaçament_conductor  57665 non-null  object
 38  Descripcio_Lloc_atropellament_vianant    57665 non-null  object
dtypes: float64(4), int64(11), object(24)
memory usage: 18.5+ MB

### Convertir el *dataset* a .csv

In [ ]:
# Directorio donde se almacenarán los archivos CSV limpios
output_dir = '/content/drive/MyDrive/TFM/clean_data'

# Crear el directorio si no existe
os.makedirs(output_dir, exist_ok=True)

# Guardar el DataFrame general como un archivo CSV
df_general4.to_csv(os.path.join(output_dir, "df.csv"), index=False)

Ahora podemos encontrar el *dataframe* limpio en la ruta '/content/drive/MyDrive/TFM/clean_data'

# Codificación de variables

In [ ]:
os.chdir('/content/drive/MyDrive/TFM/clean_data')

# Leer el archivo CSV
df = pd.read_csv('df.csv')

In [ ]:
df = df.drop(columns=['Nom_barri', 'Codi_carrer6', 'Nom_carrer', 'Longitud', 'Latitud', 'Codi_carrer3',
                      'Descripcio_causa_vianant', 'Codi_carrer2', 'Codi_carrer4', 'Descripcio_model', 'Descripcio_marca',
                      'Descripcio_color', 'Descripcio_situacio', 'Descripcio_victimitzacio', 'Descripcio_Motiu_desplaçament_vianant',
                      'Descripcio_Motiu_desplaçament_conductor', 'Descripcio_Lloc_atropellament_vianant'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62308 entries, 0 to 62307
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Numero_expedient           62308 non-null  object
 1   Nom_districte              62308 non-null  object
 2   Codi_carrer5               62308 non-null  int64
 3   Descripcio_dia_setmana     62308 non-null  object
 4   Any                        62308 non-null  int64
 5   Mes_any                    62308 non-null  int64
 6   Dia_mes                    62308 non-null  int64
 7   Hora_dia                   62308 non-null  int64
 8   Descripcio_torn            62308 non-null  object
 9   Descripcio_causa_mediata   62308 non-null  object
 10  Numero_morts               62308 non-null  int64
 11  Numero_lesionats_lleus     62308 non-null  int64
 12  Numero_lesionats_greus     62308 non-null  int64
 13  Numero_victimes            62308 non-null  int64
 14  Numero_vehicles_implicats  62308 non-null  int64
 15  Descripcio_tipus_accident  62308 non-null  object
 16  Descripcio_tipus_vehicle   62239 non-null  object
 17  Descripcio_carnet          62239 non-null  object
 18  Antiguitat_carnet          62239 non-null  object
 19  Descripcio_sexe            57665 non-null  object
 20  Edat                       57665 non-null  object
 21  Descripcio_tipus_persona   57665 non-null  object
dtypes: int64(10), object(12)
memory usage: 10.5+ MB

### Nom_districte

In [ ]:
df.Nom_districte.value_counts()

Nom_districte
Eixample               18234
Sant Martí              7733
Sants-Montjuïc          6806
Sarrià-Sant Gervasi     6687
Horta-Guinardó          4517
Les Corts               4261
Sant Andreu             3987
Ciutat Vella            3438
Nou Barris              3411
Gràcia                  3061
Desconegut               173
Name: count, dtype: int64

In [ ]:
df['Eixample']=df['Nom_districte'].str.count('Eixample')
df['Sant_Marti']=df['Nom_districte'].str.count('Sant Martí')
df['Sants_Montjuic']=df['Nom_districte'].str.count('Sants-Montjuïc')
df['Sarria_Sant-Gervasi']=df['Nom_districte'].str.count('Sarrià-Sant Gervasi')
df['Horta_Guinardo']=df['Nom_districte'].str.count('Horta-Guinardó')
df['Les_Corts']=df['Nom_districte'].str.count('Les Corts')
df['Sant_Andreu']=df['Nom_districte'].str.count('Sant Andreu')
df['Ciutat_Vella']=df['Nom_districte'].str.count('Ciutat Vella')
df['Nou_Barris']=df['Nom_districte'].str.count('Nou Barris')
df['Gracia']=df['Nom_districte'].str.count('Gràcia')
df['Districte_Desconegut']=df['Nom_districte'].str.count('Desconegut')

In [ ]:
df['Districte_Desconegut'].unique()

array([0, 1])

### Descripcio_dia_setmana

In [ ]:
mapeo_dias = {
    'Dilluns': 1,
    'Dimarts': 2,
    'Dimecres': 3,
    'Dijous': 4,
    'Divendres': 5,
    'Dissabte': 6,
    'Diumenge': 7
}

# Mapear los valores de la columna 'Descripcio_dia_setmana' a números usando el diccionario
df['Descripcio_dia_setmana'] = df['Descripcio_dia_setmana'].map(mapeo_dias)

### Descripcio_torn

In [ ]:
mapeo = {
    'Matí': 1,
    'Tarda': 2,
    'Nit': 3
}

# Mapear los valores de la columna 'Descripcio_dia_setmana' a números usando el diccionario
df['Descripcio_torn'] = df['Descripcio_torn'].map(mapeo)

### Descripcio_causa_mediata

In [ ]:
# Definir las categorías y contar sus ocurrencias
df['SinCausaMediata'] = df['Descripcio_causa_mediata'].str.count('No hi ha causa mediata')
df['Alcoholemia'] = df['Descripcio_causa_mediata'].str.count('Alcoholèmia')
df['CalzadaMalEstado'] = df['Descripcio_causa_mediata'].str.count('Calçada en mal estat')
df['VelocidadInadecuada'] = df['Descripcio_causa_mediata'].str.count('Excés de velocitat o inadequada')
df['Drogas'] = df['Descripcio_causa_mediata'].str.count('Drogues o medicament')
df['ObjetosAnimalesEnCalzada'] = df['Descripcio_causa_mediata'].str.count('Objectes o animals a la calçada')
df['FactoresMeteorologicos'] = df['Descripcio_causa_mediata'].str.count('Factors meteorològics')

### Descripcio_tipus_accident

In [ ]:
# Definir las categorías y contar sus ocurrencias
df['TA_Colision'] = df['Descripcio_tipus_accident'].str.count('Col.lisió fronto-lateral')
df['TA_Caida'] = df['Descripcio_tipus_accident'].str.count('Caiguda')
df['TA_Alcance'] = df['Descripcio_tipus_accident'].str.count('Abast')
df['TA_Colision2'] = df['Descripcio_tipus_accident'].str.count('Col.lisió lateral')
df['TA_Atropello'] = df['Descripcio_tipus_accident'].str.count('Atropellament')
df['TA_Colision3'] = df['Descripcio_tipus_accident'].str.count('Col.lisió frontal')
df['TA_Otro'] = df['Descripcio_tipus_accident'].str.count('Altres')
df['TA_ChoqueContraElementoEstático'] = df['Descripcio_tipus_accident'].str.count('Xoc contra element estàtic')
df['TA_CaidaInteriorVehiculo'] = df['Descripcio_tipus_accident'].str.count('Caiguda interior vehicle')
df['TA_Volcada'] = df['Descripcio_tipus_accident'].str.count('Bolcada')
df['TA_Alcance2'] = df['Descripcio_tipus_accident'].str.count('Abast multiple')
df['TA_SalidaDeVia'] = df['Descripcio_tipus_accident'].str.count('Sortida de via amb xoc o col.lisió')
df['TA_Persecución'] = df['Descripcio_tipus_accident'].str.count('Encalç')
df['TA_SalidaDeVia2'] = df['Descripcio_tipus_accident'].str.count('Resta sortides de via')
df['TA_SalidaDeVia3'] = df['Descripcio_tipus_accident'].str.count('Sortida de via amb bolcada')
df['TA_ChoqueContraAnimal'] = df['Descripcio_tipus_accident'].str.count('Xoc amb animal a la calçada')
df['TA_Otro2'] = df['Descripcio_tipus_accident'].str.count('Desconegut')
df['TA_SalidaDeVia4'] = df['Descripcio_tipus_accident'].str.count('Sortida de via amb atropellament')

# Sumar las columnas TA_Colision y TA_Colision2 y almacenar el resultado en la columna TA_Colision
df['TA_Colision'] = df['TA_Colision'] + df['TA_Colision2'] + df['TA_Colision3']
df['TA_SalidaDeVia'] = df['TA_SalidaDeVia2'] + df['TA_SalidaDeVia3'] + df['TA_SalidaDeVia4']
df['TA_Alcance'] = df['TA_Alcance'] + df['TA_Alcance2']
df['TA_Otro'] = df['TA_Otro'] + df['TA_Otro2']

df = df.drop(columns=['TA_Colision2', 'TA_Colision3', 'TA_SalidaDeVia2', 'TA_SalidaDeVia3', 'TA_SalidaDeVia4',
                      'TA_Alcance2', 'TA_Otro2'])

### Descripcio_tipus_vehicle

In [ ]:
df['Descripcio_tipus_vehicle'] = df['Descripcio_tipus_vehicle'].fillna('-1')

In [ ]:
# Definir las categorías y contar sus ocurrencias
df['TV_Taxi'] = df['Descripcio_tipus_vehicle'].str.count('Taxi').fillna('0').astype(int)
df['TV_Motocicleta'] = df['Descripcio_tipus_vehicle'].str.count('Motocicleta|Ciclomotor|Cuadriciclo|Quadricicle').fillna('0').astype(int)
df['TV_Automóvil'] = df['Descripcio_tipus_vehicle'].str.count('Turismo|Turisme|Todo terreno|Autocaravana|Tot terreny').fillna('0').astype(int)
df['TV_Autobús'] = df['Descripcio_tipus_vehicle'].str.count('Autobús|Autobús articulado|Microbus|Microbús|Microbus|Autocar').fillna('0').astype(int)
df['TV_Vehículo_Comercial'] = df['Descripcio_tipus_vehicle'].str.count('Furgoneta|Pick-up').fillna('0').astype(int)
df['TV_Camión'] = df['Descripcio_tipus_vehicle'].str.count('Tractocamión|Camión|Camió rígid|Tractor camió').fillna('0').astype(int)
df['TV_Bicicleta'] = df['Descripcio_tipus_vehicle'].str.count('Bicicleta|Tricicle').fillna('0').astype(int)
df['TV_Vehículo_Personal_Motorizado'] = df['Descripcio_tipus_vehicle'].str.count('Veh. mobilitat personal amb motor').fillna('0').astype(int)

df['TV_Otros'] = df['Descripcio_tipus_vehicle'].str.count('Tranvía|Tren|Tren o tramvia|Otros vehíc. a motor|Maquinaria de obras|\
                                                Maquinŕria d\'obres i serveis|Maquinària d\'obres i serveis|Altres vehicles amb motor|Altres vehicles sense motor|Carro|\
                                                Veh. mobilitat personal sense motor|Ambulància|Ambulŕncia|Desconegut').fillna('0').astype(int)

### Descripcio_carnet

In [ ]:
# Definir las categorías principales y contar sus ocurrencias
df['DC_B'] = df['Descripcio_carnet'].str.count(r'\bB\b').fillna('0').astype(int)
df['DC_Desconegut'] = df['Descripcio_carnet'].str.count('Desconegut|Es desconeix|Sense permís').fillna('0').astype(int)
df['DC_A'] = df['Descripcio_carnet'].str.count(r'\bA\b').fillna('0').astype(int)

# Contar las ocurrencias de las categorías restantes y agruparlas en una columna 'DC_Otros'
df['DC_Otros'] = 0
categorias_otras = ['BTP', 'A1', 'A2', 'AM', 'D', 'C', 'E C', 'D1', 'Llicència', 'E D', 'B1', 'E C1', 'C1', 'E B', 'E D1']
for categoria in categorias_otras:
    df['DC_Otros'] += df['Descripcio_carnet'].str.count(rf'\b{categoria}\b').fillna('0').astype(int)

### Antiguitat_carnet

In [ ]:
df['Antiguitat_carnet'] = df['Antiguitat_carnet'].fillna('-1')

In [ ]:
# Definir los límites de los grupos
bins = [0, 5, 10, 20, 30, 40, 50, 60, 100]
labels = ['AC_0-5', 'AC_5-10', 'AC_10-20',
          'AC_20-30', 'AC_30-40', 'AC_40-50',
          'AC_50-60', 'AC_más de 60']

# Iterar sobre las filas del DataFrame
for index, row in df.iterrows():
    # Inicializar contadores para cada grupo de antigüedad de carnet
    contador_antiguedad = {label: 0 for label in labels}
    # Obtener las antigüedades de carnet de la observación y dividirlas
    antiguedades = [int(x.strip()) for x in row['Antiguitat_carnet'].split(',') if x.strip().isdigit()]
    # Contar las ocurrencias de cada grupo de antigüedad de carnet para estas antigüedades
    for antiguedad in antiguedades:
        for i in range(len(bins) - 1):
            if bins[i] <= antiguedad < bins[i + 1]:
                contador_antiguedad[labels[i]] += 1
                break
    # Agregar las cuentas como nuevas columnas en el DataFrame
    for label, count in contador_antiguedad.items():
        df.at[index, label] = count

# Convertir las nuevas columnas a 'int64'
df[labels] = df[labels].astype('int64')

### Descripcio_sexe

In [ ]:
# Definir las categorías y contar sus ocurrencias
df['Hombre'] = df['Descripcio_sexe'].str.count('Home')
df['Mujer'] = df['Descripcio_sexe'].str.count('Dona')
df['Desconocido'] = df['Descripcio_sexe'].str.count('Desconegut')

### Edat

In [ ]:
df['Edat'] = df['Edat'].fillna('-1')

In [ ]:
# Definir los límites de los grupos
bins = [0, 17, 25, 35, 45, 60, float('inf')]
labels = ['Edad_1-17', 'Edad_18-25', 'Edad_26-35', 'Edad_36-45', 'Edad_46-60', 'Edad_más de 60']

# Iterar sobre las filas del DataFrame
for index, row in df.iterrows():
    # Inicializar contadores para cada grupo de edad
    contador_edades = {label: 0 for label in labels}
    # Obtener las edades de la observación y dividirlas
    edades = [int(x.strip()) for x in row['Edat'].split(',') if x.strip().isdigit()]
    # Contar las ocurrencias de cada grupo de edad para estas edades
    for edad in edades:
        for i in range(len(bins) - 1):
            if bins[i] <= edad < bins[i + 1]:
                contador_edades[labels[i]] += 1
                break
    # Agregar las cuentas como nuevas columnas en el DataFrame
    for label, count in contador_edades.items():
        df.at[index, label] = count

# Convertir las nuevas columnas a 'int64'
df[labels] = df[labels].astype('int64')

### Descripcio_tipus_persona

In [ ]:
# Definir las categorías y contar sus ocurrencias
df['TP_Conductor'] = df['Descripcio_tipus_persona'].str.count('Conductor')
df['TP_Pasajero'] = df['Descripcio_tipus_persona'].str.count('Passatger')
df['TP_Peaton'] = df['Descripcio_tipus_persona'].str.count('Vianant')
df['TP_Desconocido'] = df['Descripcio_tipus_persona'].str.count('Desconegut')

In [ ]:
df = df.drop(columns=['Nom_districte','Descripcio_sexe', 'Descripcio_causa_mediata', 'Descripcio_tipus_accident', 'Descripcio_tipus_vehicle', 'Descripcio_carnet', 'Antiguitat_carnet', 'Edat', 'Descripcio_tipus_persona'])

In [ ]:
df['Hombre'] = df['Hombre'].fillna('0').astype(int)
df['Mujer'] = df['Mujer'].fillna('0').astype(int)
df['Desconocido'] = df['Desconocido'].fillna('1').astype(int)
df['TP_Conductor'] = df['TP_Conductor'].fillna('0').astype(int)
df['TP_Pasajero'] = df['TP_Pasajero'].fillna('0').astype(int)
df['TP_Peaton'] = df['TP_Peaton'].fillna('0').astype(int)
df['TP_Desconocido'] = df['TP_Desconocido'].fillna('1').astype(int)

In [ ]:
df.isna().sum()

Numero_expedient                   0
Codi_carrer5                       0
Descripcio_dia_setmana             0
Any                                0
Mes_any                            0
Dia_mes                            0
Hora_dia                           0
Descripcio_torn                    0
Numero_morts                       0
Numero_lesionats_lleus             0
Numero_lesionats_greus             0
Numero_victimes                    0
Numero_vehicles_implicats          0
Eixample                           0
Sant_Marti                         0
Sants_Montjuic                     0
Sarria_Sant-Gervasi                0
Horta_Guinardo                     0
Les_Corts                          0
Sant_Andreu                        0
Ciutat_Vella                       0
Nou_Barris                         0
Gracia                             0
Districte_Desconegut               0
SinCausaMediata                    0
Alcoholemia                        0
CalzadaMalEstado                   0
VelocidadInadecuada                0
Drogas                             0
ObjetosAnimalesEnCalzada           0
FactoresMeteorologicos             0
TA_Colision                        0
TA_Caida                           0
TA_Alcance                         0
TA_Atropello                       0
TA_Otro                            0
TA_ChoqueContraElementoEstático    0
TA_CaidaInteriorVehiculo           0
TA_Volcada                         0
TA_SalidaDeVia                     0
TA_Persecución                     0
TA_ChoqueContraAnimal              0
TV_Taxi                            0
TV_Motocicleta                     0
TV_Automóvil                       0
TV_Autobús                         0
TV_Vehículo_Comercial              0
TV_Camión                          0
TV_Bicicleta                       0
TV_Vehículo_Personal_Motorizado    0
TV_Otros                           0
DC_B                               0
DC_Desconegut                      0
DC_A                               0
DC_Otros                           0
AC_0-5                             0
AC_5-10                            0
AC_10-20                           0
AC_20-30                           0
AC_30-40                           0
AC_40-50                           0
AC_50-60                           0
AC_más de 60                       0
Hombre                             0
Mujer                              0
Desconocido                        0
Edad_1-17                          0
Edad_18-25                         0
Edad_26-35                         0
Edad_36-45                         0
Edad_46-60                         0
Edad_más de 60                     0
TP_Conductor                       0
TP_Pasajero                        0
TP_Peaton                          0
TP_Desconocido                     0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62308 entries, 0 to 62307
Data columns (total 76 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Numero_expedient                 62308 non-null  object
 1   Codi_carrer5                     62308 non-null  int64
 2   Descripcio_dia_setmana           62308 non-null  int64
 3   Any                              62308 non-null  int64
 4   Mes_any                          62308 non-null  int64
 5   Dia_mes                          62308 non-null  int64
 6   Hora_dia                         62308 non-null  int64
 7   Descripcio_torn                  62308 non-null  int64
 8   Numero_morts                     62308 non-null  int64
 9   Numero_lesionats_lleus           62308 non-null  int64
 10  Numero_lesionats_greus           62308 non-null  int64
 11  Numero_victimes                  62308 non-null  int64
 12  Numero_vehicles_implicats        62308 non-null  int64
 13  Eixample                         62308 non-null  int64
 14  Sant_Marti                       62308 non-null  int64
 15  Sants_Montjuic                   62308 non-null  int64
 16  Sarria_Sant-Gervasi              62308 non-null  int64
 17  Horta_Guinardo                   62308 non-null  int64
 18  Les_Corts                        62308 non-null  int64
 19  Sant_Andreu                      62308 non-null  int64
 20  Ciutat_Vella                     62308 non-null  int64
 21  Nou_Barris                       62308 non-null  int64
 22  Gracia                           62308 non-null  int64
 23  Districte_Desconegut             62308 non-null  int64
 24  SinCausaMediata                  62308 non-null  int64
 25  Alcoholemia                      62308 non-null  int64
 26  CalzadaMalEstado                 62308 non-null  int64
 27  VelocidadInadecuada              62308 non-null  int64
 28  Drogas                           62308 non-null  int64
 29  ObjetosAnimalesEnCalzada         62308 non-null  int64
 30  FactoresMeteorologicos           62308 non-null  int64
 31  TA_Colision                      62308 non-null  int64
 32  TA_Caida                         62308 non-null  int64
 33  TA_Alcance                       62308 non-null  int64
 34  TA_Atropello                     62308 non-null  int64
 35  TA_Otro                          62308 non-null  int64
 36  TA_ChoqueContraElementoEstático  62308 non-null  int64
 37  TA_CaidaInteriorVehiculo         62308 non-null  int64
 38  TA_Volcada                       62308 non-null  int64
 39  TA_SalidaDeVia                   62308 non-null  int64
 40  TA_Persecución                   62308 non-null  int64
 41  TA_ChoqueContraAnimal            62308 non-null  int64
 42  TV_Taxi                          62308 non-null  int64
 43  TV_Motocicleta                   62308 non-null  int64
 44  TV_Automóvil                     62308 non-null  int64
 45  TV_Autobús                       62308 non-null  int64
 46  TV_Vehículo_Comercial            62308 non-null  int64
 47  TV_Camión                        62308 non-null  int64
 48  TV_Bicicleta                     62308 non-null  int64
 49  TV_Vehículo_Personal_Motorizado  62308 non-null  int64
 50  TV_Otros                         62308 non-null  int64
 51  DC_B                             62308 non-null  int64
 52  DC_Desconegut                    62308 non-null  int64
 53  DC_A                             62308 non-null  int64
 54  DC_Otros                         62308 non-null  int64
 55  AC_0-5                           62308 non-null  int64
 56  AC_5-10                          62308 non-null  int64
 57  AC_10-20                         62308 non-null  int64
 58  AC_20-30                         62308 non-null  int64
 59  AC_30-40                         62308 non-null  int64
 60  AC_40-50                         62308 non-null  int64
 61  AC_50-60                         62308 non-null  int64
 62  AC_más de 60                     62308 non-null  int64
 63  Hombre                           62308 non-null  int64
 64  Mujer                            62308 non-null  int64
 65  Desconocido                      62308 non-null  int64
 66  Edad_1-17                        62308 non-null  int64
 67  Edad_18-25                       62308 non-null  int64
 68  Edad_26-35                       62308 non-null  int64
 69  Edad_36-45                       62308 non-null  int64
 70  Edad_46-60                       62308 non-null  int64
 71  Edad_más de 60                   62308 non-null  int64
 72  TP_Conductor                     62308 non-null  int64
 73  TP_Pasajero                      62308 non-null  int64
 74  TP_Peaton                        62308 non-null  int64
 75  TP_Desconocido                   62308 non-null  int64
dtypes: int64(75), object(1)
memory usage: 36.1+ MB

In [ ]:
df.head()

,Numero_expedient,Codi_carrer5,Descripcio_dia_setmana,Any,Mes_any,Dia_mes,Hora_dia,Descripcio_torn,Numero_morts,Numero_lesionats_lleus,Numero_lesionats_greus,Numero_victimes,Numero_vehicles_implicats,Eixample,Sant_Marti,Sants_Montjuic,Sarria_Sant-Gervasi,Horta_Guinardo,Les_Corts,Sant_Andreu,Ciutat_Vella,Nou_Barris,Gracia,Districte_Desconegut,SinCausaMediata,Alcoholemia,CalzadaMalEstado,VelocidadInadecuada,Drogas,ObjetosAnimalesEnCalzada,FactoresMeteorologicos,TA_Colision,TA_Caida,TA_Alcance,TA_Atropello,TA_Otro,TA_ChoqueContraElementoEstático,TA_CaidaInteriorVehiculo,TA_Volcada,TA_SalidaDeVia,TA_Persecución,TA_ChoqueContraAnimal,TV_Taxi,TV_Motocicleta,TV_Automóvil,TV_Autobús,TV_Vehículo_Comercial,TV_Camión,TV_Bicicleta,TV_Vehículo_Personal_Motorizado,TV_Otros,DC_B,DC_Desconegut,DC_A,DC_Otros,AC_0-5,AC_5-10,AC_10-20,AC_20-30,AC_30-40,AC_40-50,AC_50-60,AC_más de 60,Hombre,Mujer,Desconocido,Edad_1-17,Edad_18-25,Edad_26-35,Edad_36-45,Edad_46-60,Edad_más de 60,TP_Conductor,TP_Pasajero,TP_Peaton,TP_Desconocido
0,2016S000001,144601,5,2016,1,1,0,3,0,1,0,1,2,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,1,0,1,0,0,0,0,0,1,0,0,1,0,0,0
1,2016S000002,194202,5,2016,1,1,2,3,0,1,0,1,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0
2,2016S000003,209900,5,2016,1,1,5,3,0,1,0,1,2,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,2,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0
3,2016S000004,32700,5,2016,1,1,6,1,0,3,0,3,2,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,2,0,0,0,0,1,1,0,0,0,0,0,1,2,0,0,0,1,1,1,0,1,1,1,0
4,2016S000005,269902,5,2016,1,1,8,1,0,1,0,1,2,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,2,0,0,0,2,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0

In [193]:
# Directorio donde se almacenarán los archivos CSV limpios
output_dir = '/content/drive/MyDrive/TFM/clean_data'

# Crear el directorio si no existe
os.makedirs(output_dir, exist_ok=True)

# Guardar el DataFrame general como un archivo CSV
df.to_csv(os.path.join(output_dir, "df_encoded.csv"), index=False)

Ahora podemos encontrar el *dataframe* limpio en la ruta '/content/drive/MyDrive/TFM/clean_data'

## Comprobaciones

### Inconsistencias tipo de vehículo: df_personas y df_tiposdevehiculo

In [ ]:
df6_veh = df_6.groupby('Numero_expedient')['Desc_Tipus_vehicle_implicat'].value_counts()

In [ ]:
df4_veh = df_4.groupby('Numero_expedient')['Descripcio_tipus_vehicle'].value_counts()

In [ ]:
df4_veh.reset_index()

       Numero_expedient Descripcio_tipus_vehicle  count
0           2016S000001                     Taxi      1
1           2016S000001                  Turismo      1
2           2016S000002              Motocicleta      1
3           2016S000003                  Turismo      1
4           2016S000003              Motocicleta      1
...                 ...                      ...    ...
103510      2022S008013                     Taxi      1
103511      2022S008013              Motocicleta      1
103512      2023S000004              Motocicleta      1
103513      2023S000004                Bicicleta      1
103514      2023S000550                  Turisme      1

[103515 rows x 3 columns]

In [ ]:
df6_veh.reset_index()

      Numero_expedient Desc_Tipus_vehicle_implicat  count
0          2016S000001                        Taxi      1
1          2016S000002                 Motocicleta      1
2          2016S000003                 Motocicleta      1
3          2016S000004                     Turismo      3
4          2016S000005                     Turismo      1
...                ...                         ...    ...
64084      2022S008011                     Turisme      1
64085      2022S008012                 Motocicleta      1
64086      2022S008013                 Motocicleta      1
64087      2023S000004                   Bicicleta      1
64088      2023S000550                     Turisme      1

[64089 rows x 3 columns]

In [ ]:
df4_veh.reset_index().query('Numero_expedient	== "2016S000004"')

  Numero_expedient Descripcio_tipus_vehicle  count
5      2016S000004                  Turismo      1
6      2016S000004                     Taxi      1

In [ ]:
df6_veh.reset_index().query('Numero_expedient	== "2016S000004"')

  Numero_expedient Desc_Tipus_vehicle_implicat  count
3      2016S000004                     Turismo      3

In [ ]:
df4_veh.reset_index().query('Numero_expedient	== "2016S000001"')

  Numero_expedient Descripcio_tipus_vehicle  count
0      2016S000001                     Taxi      1
1      2016S000001                  Turismo      1

In [ ]:
df6_veh.reset_index().query('Numero_expedient	== "2016S000001"')

  Numero_expedient Desc_Tipus_vehicle_implicat  count
0      2016S000001                        Taxi      1

In [ ]:
df4_veh.reset_index().query('count	>= 5').head(40)

      Numero_expedient Descripcio_tipus_vehicle  count
246        2016S000152                  Turismo      5
615        2016S000371                  Turismo      5
1235       2016S000745              Motocicleta      5
2224       2016S001337                  Turismo      5
3600       2016S002171                  Turismo      5
3674       2016S002219                  Turismo      5
3992       2016S002411                  Turismo      6
4015       2016S002424                  Turismo      5
4050       2016S002448                  Turismo      6
4166       2016S002515                  Turismo      5
4204       2016S002539              Motocicleta      7
4230       2016S002553              Motocicleta      6
4594       2016S002774              Motocicleta      6
5618       2016S003380                  Turismo      5
5738       2016S003450                  Turismo      5
5946       2016S003576                  Turismo      8
6247       2016S003758                  Turismo      5
6393       2016S003844              Motocicleta      5
7316       2016S004405              Motocicleta      5
8168       2016S004915              Motocicleta      7
8303       2016S004993                  Turismo      5
9097       2016S005456              Motocicleta      8
9099       2016S005457              Motocicleta      5
9402       2016S005640                  Turismo      5
9654       2016S005790                  Turismo      7
9660       2016S005794                  Turismo      5
9986       2016S005989                  Turismo      5
10018      2016S006009                  Turismo      5
10765      2016S006461              Motocicleta      8
11020      2016S006617                  Turismo      5
11482      2016S006881                  Turismo      5
11662      2016S006995                  Turismo      8
11969      2016S007176                  Turismo      6
11971      2016S007178                  Turismo      5
13389      2016S008037                  Turismo      5
13437      2016S008067                  Turismo      6
13438      2016S008067              Motocicleta      5
14853      2016S008916                  Turismo      5
15177      2016S009113                  Turismo      5
15542      2016S009326                  Turismo      6

In [ ]:
df4_veh.reset_index().query('Numero_expedient	== "2016S006461"')

      Numero_expedient Descripcio_tipus_vehicle  count
10765      2016S006461              Motocicleta      8
10766      2016S006461                  Turismo      1

In [ ]:
df6_veh.reset_index().query('Numero_expedient	== "2016S006461"')

Empty DataFrame
Columns: [Numero_expedient, Desc_Tipus_vehicle_implicat, count]
Index: []